### ISSUE TITLE
Support installing rubies in the implementation-x.y.z form?

### ISSUE THREAD

**Issue by gregkare** [postmodern/ruby-install#102]
Once in a while when I use ruby-install I forget that I shouldn't put a dash between the Ruby implementation and the version, the way it's done in `.ruby-version` files. It happens more when I'm reinstalling a version (in today's occurrence I've deleted my ruby-2.0.0-p353 because it was using an old GCC 4.2 to compile C extensions and recompiled it with clang), I tend to copy & paste from chruby's output.

```
$ ruby-install ruby-2.0.0-p353
ruby-install: unsupported ruby: ruby-2.0.0-p353
```

When I see that message I remember I'm supposed to do it like this:

```
$ ruby-install ruby 2.0.0-p353
```

Do you think it would be worth contributing a pull request that supports both notations? I haven't looked at the code yet but I'm assuming supporting a Ruby version as one or two arguments wouldn't add that much complexity.

What do you think?

**Comment by postmodern** [comment]
Support coming for this in 0.6.0.
