### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by epinault** [postmodern/ruby-install#128]
On OSX Maverick (10.9.1), using bash shell  3.2.51(1), and ruby-install 0.4.0

I love ruby-install but does not seem to work with proxy.

I have my http_proxy and https_proxy correctly and can do a curl manually and get the files.. but does not seem to work when running  "ruby-install ruby 2.1.1"

I get bunch of timeout. So I suspect those ENV variable are not passed/defined in the shell executed by ruby-install

**Comment by postmodern** [comment]
If anyone wants to submit a PR to pass proxy options to both `curl` and `wget`, I'd accept it!

**Comment by skade** [comment]
I hit this issue when ruby-install tries to install via brew. Calling brew directly works.

**Comment by sofaking** [comment]
As an addition to @skade comment, I tried to preserve proxy settings via sudoers file (```/private/etc/sudoers```). You'll need to add your settings to ```env_keep``` section.
