### ISSUE TITLE
Re-compile against new openssl for Heartbleed

### ISSUE THREAD

**Issue by jish** [postmodern/ruby-install#140]
I've heard some say that your local copy of Ruby is fine, others say it needs to be re-compiled. Just to be on the safe side, if I wanted to re-compile Ruby locally, what would I have to do to ensure that I re-compile with the newest version of OpenSSL on Mac OS?

```
brew update
brew upgrade ruby-install
ruby-install ruby
```

Is that sufficient / correct?

**Comment by indirect** [comment]
It's probably easiest to just print `OpenSSL::OPENSSL_LIBRARY_VERSION`, which is the version of OpenSSL that your running Ruby is using (as opposed to `OpenSSL::OPENSSL_VERSION`, which is what was present back when you originally compiled Ruby).
