### ISSUE TITLE
Drop support for maglev

### ISSUE THREAD

**Issue by postmodern** [postmodern/ruby-install#167]
[maglev is unofficially End-of-Lifed](https://groups.google.com/forum/m/#!topic/maglev-discussion/CADHEkDx-gA)

> At this time, GemTalk has no plans to turn MagLev into a commercial product and we will not dedicate resources to its on-going development.

**Comment by havenwood** [comment]
This is resolved now that [v0.7.0](https://github.com/postmodern/ruby-install/releases/tag/v0.7.0) has been released.
