### ISSUE TITLE
Add --update option

### ISSUE THREAD

**Issue by postmodern** [postmodern/ruby-install#175]
Add an `--update` option to download new versions and checksums from [ruby-versions](https://github.com/postmodern/ruby-versions). These should be downloaded to either `~/.cache/` or `/var/cache`. The ruby-install code should determine which directory to use for the checksums/versions based on their timestamps.

**Comment by josh-nz** [comment]
I'm not super up-with-the-play on *nix conventions, but could you not just update the files that hold the initial checksums? If you were then to subsequently update ruby-install you'd still have the latest checksums. The reason I mention this is that personally I find a lot of programs create dot directories and sometimes you don't know what program they belong to. For example I have `~/.local` and `~/.m2` (I happen to have worked out what these are used for). The majority of the dot directories are named after the app, but that's still an explosion of dot directories. If you're going to proceed with the dot directory idea, my vote would be to use a meaningful name, such as `.ruby-install`. `.cache` is very generic and anything could live in here.

**Comment by 13k** [comment]
@josh-nz I believe using `~/.cache` is the right approach on Linux, since it conforms to the freedesktop's [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). Even better would be to use `$XDG_CACHE_HOME` (with a fallback).

On OS X, usually apps write files to `~/Library/Caches`. Per Apple's [developer manual page describing the file system](https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1), it's the appropriate place to put these kind of files.

**Comment by postmodern** [comment]
OK, here is what I'm thinking currently. ruby-install should re-download the version/checksum files into `~/.cache/ruby-install` on every run (except for `--help` or `--version`). To prevent constantly re-downloading the same files, we should only re-download the file if it's older than one day. If `ruby-install` is invoked to list current stable versions, all `stable.txt` files should be re-downloaded. If `ruby-install RUBY` is invoked, the version/checksum files for `RUBY` should be re-downloaded. Thoughts on any usability issues this might introduce?

**Comment by nengxu** [comment]
@postmodern Today I'm still not able to ruby-install ruby-2.2.2, using the head of master branch.

The --update option is not there:

[neng@dolphin:~]$ ruby-install --update
ruby-install: unrecognized option --update

Please tell me how to do to get 2.2.2 ruby-installed? Thanks.

**Comment by aprescott** [comment]
@nengxu does `ruby-install ruby 2.2.2` not work for you?

**Comment by nengxu** [comment]
@aprescott Yeah, I forgot to try this. I'm running out of time to go through the whole process. But notice this:

[neng@dolphin:~]$ ruby-install ruby 2.2.2
>>> Installing ruby 2.2.2 into /home/neng/.rubies/ruby-2.2.2 ...
>>> Installing dependencies for ruby 2.2.2 ...
>>> Downloading http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.bz2 into /home/neng/src ...
>>> Verifying ruby-2.2.2.tar.bz2 ...
*** No md5 checksum for /home/neng/src/ruby-2.2.2.tar.bz2
*** No sha1 checksum for /home/neng/src/ruby-2.2.2.tar.bz2
*** No sha256 checksum for /home/neng/src/ruby-2.2.2.tar.bz2
*** No sha512 checksum for /home/neng/src/ruby-2.2.2.tar.bz2
>>> Extracting ruby-2.2.2.tar.bz2 to /home/neng/src/ruby-2.2.2 ...

**Comment by aprescott** [comment]
Right, because the checksums for 2.2.2 aren't available. You can't get them automatically until `--update` exists. But that won't stop you from installing 2.2.2.

If you know the checksum (from a trusted source) and want to manually specify it as part of the installation process, you can include it as an option to `ruby-install`. From `ruby-install --help`:

```ruby
	-m, --md5 MD5		MD5 checksum of the Ruby archive
	    --sha1 SHA1		SHA1 checksum of the Ruby archive
	    --sha256 SHA256	SHA256 checksum of the Ruby archive
	    --sha512 SHA512	SHA512 checksum of the Ruby archive
```

**Comment by postmodern** [comment]
So I attempted to use wget/curl's timestamp checking functionality, unfortunately `raw.githubusercontent.com` does not support the `Last-Modified` header, so wget/curl will re-download anyways. Also, `raw.githubusercontent.com` isn't as fast as I hoped. Looks like I will have to fallback to my original strategy of re-downloading if the file(s) are more than an hour old.

**Comment by postmodern** [comment]
See the [cache branch](https://github.com/postmodern/ruby-install/tree/cache) for my WIP.

**Comment by 13k** [comment]
@postmodern would you consider using a CDN service, like https://bintray.com (it's free for open source) or even S3 (paid)?

uploading the versions file(s) could be done automatically via Travis CI, in a similar fashion as [how ruby-build uploads to S3](https://github.com/sstephenson/ruby-build/blob/e932d47195d76d6be9635a012056069e794039e0/script/s3-put)

**Comment by postmodern** [comment]
@13k you can specify your own mirror with the `-M,--mirror` option. ruby-core already uses http://cache.ruby-lang.org/ which is hosted by fastly and JRuby/Rubinius already host their releases on S3.

**Comment by postmodern** [comment]
@13k hmm I will consider hosting the version/checksum files on another service when we hit github's bandwidth limit. The files are quite small and ruby-install should only update them once every couple hours. Still, it would be able to properly cache them using `If-Modified-Since` headers.

**Comment by timuckun** [comment]
Any progress on this. I just installed from brew and when I type ruby-install I get the following.

```bash
Latest ruby versions:
  ruby:
    2.0.0-p647
    2.1.7
    2.2.3
  jruby:
    9.0.0.0
  rbx:
    2.2.10
    2.3.0
    2.4.1
    2.5.8
  maglev:
    1.0.0
  mruby:
    1.1.0
```

There is no option to upgrade the list so I now have to come here to github and check the latest versions.

**Comment by vitorgalvao** [comment]
@timuckun If all you want is to install the latest ruby, you can do it pretty easily:

```bash
latest_ruby=$(curl --silent 'https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/stable.txt' | tail -1)
ruby-install ruby "${latest_ruby}"
```

Although yes, it would naturally be best to be able to do so manually.

**Comment by nengxu** [comment]
@vitorgalvao This kind of manual long command may not sound "pretty easily"?

**Comment by timuckun** [comment]
@vitorgalvao I think an --update option would be much more intuitive

**Comment by vitorgalvao** [comment]
> This kind of manual long command may not sound "pretty easily"?

“Manual”?

```bash
update_ruby() {
  local latest_ruby=$(curl --silent 'https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/stable.txt' | tail -1)
  ruby-install ruby "${latest_ruby}"
}
```

There, add it to your shell’s startup files. Run `update_ruby` when you want.

> I think an --update option would be much more intuitive

Yes, and like I said:

> Although yes, it would naturally be best to be able to do so natively.

You had a clear complaint, @timuckun (emphasis mine):

> There is no option to upgrade the list **so I now have to come here to github and check the latest versions**.

I gave you simple way to not have to do that anymore. Yes, we would all prefer this to be native, but since it currently isn’t supported, would you rather not have an easy alternative for the mean time?

**Comment by postmodern** [comment]
I've been working in the [cache](https://github.com/postmodern/ruby-install/tree/cache) branch and am now re-arranging the code. The main blocker is that raw.githubusercontent.com does not support the `Last-Modified` header, so I can't do [real timestamp caching](http://blog.yjl.im/2012/03/downloading-only-when-modified-using_23.html) with `wget`/`curl`. This leaves me with the following alternatives:

1. Always download the versions/checksums on every invocation. Downside is this slows down listing of current versions.
2. Only download if files are older than some time frame (maybe one hour or one day?). Upside is we avoid re-downloading the files. Downside is listing would still trigger a download.
3. Add an explicit `--update` option to update the versions/checksums and skip the whole auto-updating logic.

**Comment by timuckun** [comment]
@postmodern 

I think an hour or two cache would be sufficient.  Let's face it we don't do a ruby install every day. Chances are we do a ruby install when we are setting up a new machine and when we want to upgrade. If I am setting up a new laptop I might install a couple of versions but that's about it.  

Having said that you could also add a --update option to force the update or for those occasions when I want to see if a new version of jruby is out.  Once I run the update I might do an install and the caching feature would prevent a fresh pull.

**Comment by postmodern** [comment]
OK, I've decided to hold off on auto-updating and just provide an option for explicit updating. My logic is the user is wants to install a new version, specifically because they heard a new version was recently released. So it's not too much to require the user specify `--update`. Also thought about naming it `--sync` or `--update-cache`. May eventually add the ability to remove/update previously installed rubies.

**Comment by timuckun** [comment]
:+1:

**Comment by postmodern** [comment]
Got a prototype of the new code working-ish. Wondering if we should explicitly check for the `~/.cache/ruby-install/` directory and download everything, or download on-the-fly when we access individual files and they are missing?

**Comment by postmodern** [comment]
Checkout the [ruby-versions](https://github.com/postmodern/ruby-install/tree/ruby-versions) branch for a working-ish `--update` option. Also note it will auto-download the version files if they are missing (ex: on first run).

**Comment by postmodern** [comment]
Merged ruby-versions into 0.6.0 branch. Getting ready to merge into master, provided no outstanding negative feedback.

**Comment by postmodern** [comment]
Last minute @havenwood and I decided to go with `--latest` to avoid implying that we're updating ruby-install itself or any previously installed rubies.

**Comment by postmodern** [comment]
aaaand 0.6.0 has been released! Happy `--latest`ing.

**Comment by timuckun** [comment]
Yea!

Thanks for all the hard work
