### ISSUE TITLE
Switch to using https://s3.amazonaws.com/releases.rubini.us for rbx?

### ISSUE THREAD

**Issue by postmodern** [postmodern/ruby-install#179]
Now that jruby [encourages](https://twitter.com/jruby/status/525726366533443584) using https://s3.amazonaws.com/jruby.org, should we also switch to using https://s3.amazonaws.com/releases.rubini.us as well? /cc @brixen

**Comment by igalic** [comment]
this issue seems a little out of date…

**Comment by igalic** [comment]
hmhmhm… cool!
but i suppose that was not the cause of ruby-install only showing the following versions:
```
  rbx:                                                                                                                                  
    2.2.10                                                                                                                              
    2.3.0                                                                                                                               
    2.4.1                                                                                                                               
    2.5.8                                                                                                                               
```

**Comment by postmodern** [comment]
@igalic yes, ruby-install 0.5.x still uses versions that are bundled with ruby-install. I've been working on a branch that can download new versions/checksums from [ruby-versions](https://github.com/postmodern/ruby-versions).
