### ISSUE TITLE
rbx 2.3 fails to build on Yosemite due to llvm config error

### ISSUE THREAD

**Issue by swrobel** [postmodern/ruby-install#184]
As originally reported by @willcosgrove on https://github.com/postmodern/ruby-install/issues/181

`~/src/rubinius-2.3.0/configure.log`:

```
[2014-11-04 15:33:58] Configuring Rubinius...
[2014-11-04 15:33:58] Command line: "--prefix=/Users/swrobel/.rubies/rbx-2.3.0 --with-opt-dir=/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/libyaml:/usr/local/opt/gdbm"
[2014-11-04 15:33:58] Checking gcc:
[2014-11-04 15:33:58]  found
[2014-11-04 15:33:58] Checking g++:
[2014-11-04 15:33:58]  found
[2014-11-04 15:33:58] Checking bison:
[2014-11-04 15:33:58]  found
[2014-11-04 15:33:58] ---

Detected old configuration settings, forcing a clean build

---
[2014-11-04 15:33:59]   Checking for 'llvm-config': 
[2014-11-04 15:33:59] not found
[2014-11-04 15:33:59]*** ERROR ABORT: unable to set up LLVM
```

**Comment by taf2** [comment]
brew install llvm
rvm install rbx -- --llvm-config /usr/local/opt/llvm/bin/llvm-config

**Comment by hickscorp** [comment]
With @taf2 suggestion:

```
brew install llvm
rvm install rbx -- --llvm-config /usr/local/opt/llvm/bin/llvm-config
```

I like this solution, because it avoids linking the brew version of LLVM into my system.
However, i'm now very puzzled by the following error message after i ran bundle to install my gems and started my Rails (4.2) application:

```
dyld: lazy symbol binding failed: Symbol not found: _capi_get_constant
  Referenced from: ~/.rvm/gems/rbx-2.5.2@global/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _capi_get_constant
  Referenced from: ~/.rvm/gems/rbx-2.5.2@global/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

[1]    60885 trace trap  rails s
```

Any similar experience with a clean workaround please?

**Comment by krisleech** [comment]
rbx (~> 2.5) needs an older LLVM (~> 3.5) then is installed by latest xcode or brew. Check the system LLVM is okay or you have an older brew installed version with `ls /usr/local/Cellar/llvm`.

```
brew upgrade ruby-install --HEAD
ruby-install rbx -- --llvm-config=/usr/local/Cellar/llvm/3.5.1/bin/llvm-config
```

Good luck.

**Comment by paddor** [comment]
Got it to compile and install using:

```
brew install homebrew/versions/llvm35
brew upgrade ruby-install --HEAD
ruby-install rbx -- --llvm-config=/usr/local/lib/llvm-3.5/bin/llvm-config
```

**Comment by jzaleski** [comment]
Got `rbx-3.27` to work on El Capitan with the following:
```
brew install homebrew/versions/llvm35
rvm install rbx-3.27 -- --llvm-config /usr/local/opt/llvm35/bin/llvm-config-3.5
```
I would assume this should work for other versions of Rubinius / OSX as well.

**Comment by CodeGnome** [comment]
## What Works
This now seems to work on macOS Sierra when using the latest versions of both Rubinius and the most recent LLVM package from Homebrew (currently 3.9.0). For example:

    brew install llvm
    ruby-install --latest rbx

## What Doesn't
Without using the the latest versions, you get the prior behavior of:

```
Checking clang++: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': executing "/usr/local/Cellar/llvm/3.9.0/bin/llvm-config" failed
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
!!! Configuration of rbx 3.67 failed!
```

**Comment by havenwood** [comment]
Recent versions of Rubinius no longer seem to have this issue.

**Comment by postmodern** [comment]
Rubinius support was removed due to inactivity (see #435). Closing this.
