### ISSUE TITLE
Unable to require openssl.... We are unable to install any gems.

### ISSUE THREAD

**Issue by collegeimprovements** [postmodern/ruby-install#194]
Hi we ran ruby-install ruby command and it installed ruby 2.1.3 perfectly.
But we are unable to progress further due to openssl error.
Please guide us.

```
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
```

**Comment by coalwater** [comment]
So I installed a fresh debian system today, and I got this exact issue again, openssl installed, but not used when ruby is compiled, found out the issue was the missing `libssl-dev` library, I needed to install it and recompile agian then every thing worked fine.

**Comment by postmodern** [comment]
@coalwater that is odd, since `libssl-dev` is listed in [ruby/dependencies.txt](https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/share/ruby-install/ruby/dependencies.txt#L1).

**Comment by coalwater** [comment]
what is supposed to happen when a dependency isn't met? cause I tested now what i have and what I don't have, found multiple missing libs, I tried to reinstall `ruby-install` and it reinstalled fine without complaining about missing deps

    dpkg-query: package 'libgdbm-dev' is not installed and no information is available
    dpkg-query: package 'libreadline-dev' is not installed and no information is available
    dpkg-query: package 'libncurses5-dev' is not installed and no information is available

**Comment by coalwater** [comment]
Ok nvm I know what's wrong, I always install with `--no-install-deps` because I don't use `sudo` with ruby-install, cause if i do, ruby installs in a system directory

**Comment by postmodern** [comment]
@coalwater ruby-install is smart enough to invoke sudo for you, if it's not running as root. https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/share/ruby-install/ruby-install.sh#L32-L37 https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/share/ruby-install/ruby-install.sh#L104

Maybe it's also an issue with your user's access to `sudo`?

**Comment by coalwater** [comment]
yea well debian by default doesn't have `sudo`, so i guess I made a habit of installing `build-essential` and `ruby-install` while being as root, then switching to the user and running with `--no-install-deps` to avoid the errors, didn't realize it would be this bad.
Could we like make an option, something that would only install the dependencies without any rubies, I'm not so good with bash scripting but I could manage something and let you review it.

**Comment by famousky** [comment]
Similar error here, but in my case I installed successfully selected version of ruby using standard $ ruby-install ruby VERSION " . But now when I try to run *gem install rails*, I am getting same error:

ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources

**Comment by coalwater** [comment]
What exactly did you run to install ruby? also does

    sudo apt-get install build-essential zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev libncurses5-dev libffi-dev
install any thing for you ?

**Comment by famousky** [comment]
@coalwater I don't use apt-get or Homebrew as alternative.

Same as @collegeimprovements I am on OS X Yosemite 10.10

In this case can I just simply run **sudo install build-essential zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev libncurses5-dev libffi-dev** ?

**Comment by coalwater** [comment]
Well like mentioned in a previous comment, the dependencies are listed in [ruby/dependencies.txt][dependencies-link]

[dependencies-link]: https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/share/ruby-install/ruby/dependencies.txt#L4

**Comment by famousky** [comment]
@coalwater does it mean it should automatically fetch them all? Or I should manually install each of them? Not sure what my next step is.

**Comment by famousky** [comment]
@coalwater just saw you corrected your reply. I see I have already one **openssl** file in **/usr/bin/**
Looks like my system don't see it?

**Comment by famousky** [comment]
@postmodern & @coalwater trying to investigate and fix it without any luck. Btw, how does the Ruby's OpenSSL works? Is it tied somehow to **/Library/Ruby/Gems/2.0.0/gems/rubygems-update-2.4.6/lib/rubygems/ssl_certs** I have this dir for system Ruby. Was thinking to updating it but I don't want to really mess with system Ruby.

**Comment by famousky** [comment]
Well, for now reinstalled all, installed homebrew and did all installations again, however not a big fan have one more thing in my system, but it did the job and now I can continue my work. Still would like to know why ruby did not see openssl..

**Comment by havenwood** [comment]
@famousky The OS X system OpenSSL is not an option. MRI requires an OpenSSL version >= 1.0.1. Apple has also deprecated OpenSSL as of Lion 10.7 in favor of Common Crypto.

**Comment by Meekohi** [comment]
Leaving this here for any other poor schmuck who has wasted an entire day on this:

Seems like newer versions of OSX deprecated openSSL, leaving lots of stuff broken. You need to reinstall ruby, but specify exactly where your openSSL libraries are for it to be compiled with them. If you're using rvm then that looks like:

```
rvm reinstall 2.3.0 --with-openssl-dir=/usr/local/opt/openssl
```

If you're using homebrew, then a quick shortcut to where your libraries are is:

```
brew install openssl
rvm reinstall 2.3.0 --with-openssl-dir=`brew --prefix openssl`
```

**Comment by JPCodes** [comment]
@Meekohi, unfortunately this didn't work for me. Knowing that this is an OSX issue is encouraging though, maybe we'll get a patch for it soon.

**Comment by ajackiewicz** [comment]
@meekohi that worked for me thanks a ton!

**Comment by akhil-trantor** [comment]
Recently I was struggling with ruby installations due to the recent auto-update in openssl version from 1.0 to 1.1.
I found out that the ruby version < 2.4 does not work with openssl version > 1.0.

I was not even able to revert back the openssl to 1.0 version because other libs has dependencies on it. 
 
No other solution except the one given below worked for me:


`brew install rbenv/tap/openssl@1.0
rvm reinstall 1.9.3-p551 --with-openssl-dir='/usr/local/opt/openssl@1.0'
gem update --system
`

Now my ruby runs with openssl 1.0 whereas all other libraries are running on the default openssl version 1.1.

**Comment by hosamaly** [comment]
I had to update `CPPFLAGS` and `LDFLAGS` to get it working...
https://stackoverflow.com/a/61915791/41283

**Comment by justAnotherDev** [comment]
for those looking for a `ruby-install`/`chruby` friendly solution, this worked for me:

```
rm -rf ~/.rubies/ruby-2.6.3
ruby-install ruby-2.6.3 -- --with-openssl-dir=`brew --prefix openssl`
```

**Comment by postmodern** [comment]
FYI ruby-install already passes `--with-opt-dir` with a list of `brew --prefix ...` dirs. Did CRuby change/deprecate `--with-opt-dir` in favor of `--with-openssl-dir`?
https://github.com/postmodern/ruby-install/blob/3cb283cb587378f1065bf8de4c8b573a3a111423/share/ruby-install/ruby/functions.sh#L24-L32

**Comment by postmodern** [comment]
Found why 0.8.0 wasn't correctly passing in `--with-opt-dir=$(brew --prefix ...)`. 0.8.1 will be released shortly.
e68a6ab1d27a8f90fef096e7516fa437801dfe67

**Comment by postmodern** [comment]
ruby-install 0.8.1 has been released, which should fix any issues with 0.8.0 and openssl.

**Comment by sushma-4** [comment]
I'm still seeing the same error after rebuilding it with ssl. What to do?

**Comment by MtnBiker** [comment]
ruby-install --version
ruby-install: 0.8.1

➜ chruby ruby-3.0.3
Ignoring aliyun-sdk-0.8.0 because its extensions are not built. Try: gem pristine aliyun-sdk --version 0.8.0
Ignoring bcrypt-3.1.16 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.16
Ignoring bigdecimal-3.0.2 because its extensions are not built. Try: gem pristine bigdecimal --version 3.0.2
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.7.7 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.7
Ignoring bootsnap-1.7.6 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.6
Ignoring bootsnap-1.7.4 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.4
Ignoring bootsnap-1.7.3 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.3

etc.

after using `➜ ruby-install ruby 3.0.3 -- --with-openssl-dir=/usr/include`

**Comment by postmodern** [comment]
@MtnBiker probably because those gems existed in the gem home before installing ruby-3.0.3 and are incompatible. Try running `gem pristin --extensions` to rebuild them.

**Comment by MtnBiker** [comment]
@postmodern. I had tried `gem pristine --all` to no effect. Now I'll try `gem pristin --extensions`. I didn't expect that to go. Assumed a misspelling. But it ran. `Building native extensions. This could take a while...` and it did take a while.

`Skipped openssl-2.2.0, it is a default gem` among other similar notes.

`ruby-install ruby 3.0.3` while in ruby 3.0.2:

*** Following extensions are not compiled:
openssl:
	Could not be configured. It will not be installed.
	Check ext/openssl/mkmf.log for more details.

I can't find any recent `mkmf.log` using Spotlight.

    >>> Successfully installed ruby 3.0.3 into ~/.rubies/ruby-3.0.3

    xxx on  main via 💎 ruby-3.0.2 took 6m 32s
    ➜ chruby ruby-3.0.3
    Ignoring aliyun-sdk-0.8.0 because its extensions are not built. Try: gem pristine aliyun-sdk --version 0.8.0
    Ignoring bcrypt-3.1.16 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.16
    Ignoring bigdecimal-3.0.2 because its extensions are not built. Try: gem pristine bigdecimal --version 3.0.2
    Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
    Ignoring bootsnap-1.7.7 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.7
    Ignoring bootsnap-1.7.6 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.6
    Ignoring bootsnap-1.7.4 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.4
    Ignoring bootsnap-1.7.3 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.3
    Ignoring bootsnap-1.7.2 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.2
    Ignoring bootsnap-1.5.1 because its extensions are not built. Try: gem pristine bootsnap --version 1.5.1
    Ignoring byebug-11.1.3 because its extensions are not built. Try: gem pristine byebug --version 11.1.3
    Ignoring date-3.1.1 because its extensions are not built. Try: gem pristine date --version 3.1.1
    Ignoring debug_inspector-1.1.0 because its extensions are not built. Try: gem pristine debug_inspector --version 1.1.0
    Ignoring debug_inspector-1.0.0 because its extensions are not built. Try: gem pristine debug_inspector --version 1.0.0
    Ignoring ffi-1.15.3 because its extensions are not built. Try: gem pristine ffi --version 1.15.3
    Ignoring ffi-1.15.0 because its extensions are not built. Try: gem pristine ffi --version 1.15.0
    Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
    Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
    Ignoring fiddle-1.0.9 because its extensions are not built. Try: gem pristine fiddle --version 1.0.9
    Ignoring io-console-0.5.9 because its extensions are not built. Try: gem pristine io-console --version 0.5.9
    Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6
    Ignoring llhttp-ffi-0.3.1 because its extensions are not built. Try: gem pristine llhttp-ffi --version 0.3.1
    Ignoring mimemagic-0.4.3 because its extensions are not built. Try: gem pristine mimemagic --version 0.4.3
    Ignoring msgpack-1.4.2 because its extensions are not built. Try: gem pristine msgpack --version 1.4.2
    Ignoring msgpack-1.3.3 because its extensions are not built. Try: gem pristine msgpack --version 1.3.3
    Ignoring nio4r-2.5.8 because its extensions are not built. Try: gem pristine nio4r --version 2.5.8
    Ignoring nio4r-2.5.7 because its extensions are not built. Try: gem pristine nio4r --version 2.5.7
    Ignoring nio4r-2.5.4 because its extensions are not built. Try: gem pristine nio4r --version 2.5.4
    Ignoring nokogiri-1.10.10 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.10
    Ignoring ovirt-engine-sdk-4.4.1 because its extensions are not built. Try: gem pristine ovirt-engine-sdk --version 4.4.1
    Ignoring pg-1.2.3 because its extensions are not built. Try: gem pristine pg --version 1.2.3
    Ignoring psych-4.0.1 because its extensions are not built. Try: gem pristine psych --version 4.0.1
    Ignoring puma-5.4.0 because its extensions are not built. Try: gem pristine puma --version 5.4.0
    Ignoring puma-5.2.2 because its extensions are not built. Try: gem pristine puma --version 5.2.2
    Ignoring puma-5.1.1 because its extensions are not built. Try: gem pristine puma --version 5.1.1
    Ignoring puma-4.3.7 because its extensions are not built. Try: gem pristine puma --version 4.3.7
    Ignoring puma-3.12.6 because its extensions are not built. Try: gem pristine puma --version 3.12.6
    Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
    Ignoring readline-ext-0.1.2 because its extensions are not built. Try: gem pristine readline-ext --version 0.1.2
    Ignoring rgeo-2.3.0 because its extensions are not built. Try: gem pristine rgeo --version 2.3.0
    Ignoring rgeo-2.2.0 because its extensions are not built. Try: gem pristine rgeo --version 2.2.0
    Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
    Ignoring sqlite3-1.4.2 because its extensions are not built. Try: gem pristine sqlite3 --version 1.4.2
    Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7
    Ignoring websocket-driver-0.7.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.5
    Ignoring websocket-driver-0.7.3 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.3

I've been manually deleting the ruby-3.0.3 install `~/.rubies/ruby-3.0.3/`. Is that OK?

Thank you for responding.

**Comment by MtnBiker** [comment]
Read through these comments again and tried

    xxx on  main via 💎 ruby-3.0.2 took 16s
    ➜ echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

    xxx on  main via 💎 ruby-3.0.2
    ➜ export LDFLAGS="-L/usr/local/opt/openssl@3/lib"

    xxx on  main via 💎 ruby-3.0.2
    ➜  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

    ruby-install ruby-3.0.3 -- --with-openssl-dir=`brew --prefix openssl` 

And get same. End of the install terminal log

[partial_install_log.txt](https://github.com/postmodern/ruby-install/files/7764341/partial_install_log.txt)
