### ISSUE TITLE
Not listing latest rubies

### ISSUE THREAD

**Issue by josh-nz** [postmodern/ruby-install#198]
I have ruby-install 0.5.0 via homebrew. I've updated brew and updated ruby-install via brew just now. It reports I have the latest version.

Running ruby-install reports the latest ruby version to be 2.1.3, which appears to be quite out of date. https://www.ruby-lang.org/en/ reports 2.1.4 being released as far back as 27 Oct 2014, so 2.1.3 must be older still.

Why is ruby-install not reporting 2.2.0 as the latest version? (Released 25 Dec 2014).

For full reference, I get:
```
Latest ruby versions:
  ruby:
    1.9.3-p547
    2.0.0-p576
    2.1.3
  jruby:
    1.7.16
  rbx:
    2.2.10
  maglev:
    1.0.0
  mruby:
    1.0.0
```
when running ruby-install

**Comment by havenwood** [comment]
To get the latest definitions run:
```sh
brew reinstall ruby-install --HEAD
```
There are plans (#175) to add an `--update` option that syncs to the latest versions and checksums from the [ruby-versions] repository to keep up to date with Rubies being released.
[ruby-versions]: https://github.com/postmodern/ruby-versions

**Comment by josh-nz** [comment]
Ok. The readme seems misleading then. I interpreted this:

Does not require updating every time a new Ruby version comes out.

As meaning I didn't need to update ruby-install. To what does the above feature refer to then?

**Comment by aprescott** [comment]
It means you can run `ruby-install ruby 2.2.0` and it'll install 2.2.0 even if `ruby-install` doesn't have it in its list of known versions.

**Comment by josh-nz** [comment]
RIght, that was my conclusion from havenwood's post above. I also did install ruby 2.2.0 yesterday even though it wasn't in the list of known versions, but it warned about the checksum not being known, obviously. I guess in this case I could have provided the --md5 option. Strange there is no --sha option? Is md5 ok in this situation to avoid collisions?

**Comment by havenwood** [comment]
In addition to `--md5` there're options for `--sha1`, `--sha256` and `--sha512`. For unknown Rubies you can specify one or more checksums to be validated. All four are validated when the version is known.

**Comment by josh-nz** [comment]
Doh, should have `ruby-install --help` first! Could I have an attempt at updating the readme to be a touch more verbose around new rubies and submit a pull request?

**Comment by havenwood** [comment]
Pull requests are welcome. Check out the [contributing guidelines](../blob/master/CONTRIBUTING.md#contributing).

It might be worth waiting for the `--update` option to polish the readme for clarity, I don't know.
