### ISSUE TITLE
does installation require user to be sudoer?

### ISSUE THREAD

**Issue by mikeni** [postmodern/ruby-install#201]
In the documentation in README, it says

wget -O ruby-install-0.5.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz
tar -xzvf ruby-install-0.5.0.tar.gz
cd ruby-install-0.5.0/
sudo make install

if my user is not allowed to sudo, is there anyway to install?
without sudo I get errors such as
or dir in `find bin share -type d`; do mkdir -p /usr/local/$dir; done
for file in `find bin share -type f`; do cp $file /usr/local/$file; done
cp: cannot create regular file ‘/usr/local/bin/ruby-install’: Permission denied
cp: cannot create regular file ‘/usr/local/share/man/man1/ruby-install.1’: Permission denied
cp: cannot create regular file ‘/usr/local/share/ruby-install/maglev/dependencies.txt’: Permission denied
cp: cannot create regular file ‘/usr/local/share/ruby-install/maglev/functions.sh’: Permission denied

**Comment by postmodern** [comment]
You can run `PREFIX=~/somewhere make install` and add `export PATH=$PATH:~/somewhere/bin` to your `.bashrc`/`.zshrc`.

**Comment by mikeni** [comment]
Thank you for the response.

**Comment by postmodern** [comment]
Also by default ruby-install will try to install packages from the package manager, which requires permission. You may also want to skip that step with `--no-install-deps`.

**Comment by mikeni** [comment]
works like a charm, thanks again.

**Comment by mikeni** [comment]
question, i have installed the ruby however do I need to do the same with chruby?  chruby is not finding the rubies I have just installed into /home/mike/.rubies/ruby-2.2.0
