### ISSUE TITLE
doesn't keep up to date with jruby

### ISSUE THREAD

**Issue by timuckun** [postmodern/ruby-install#204]
seems to be a couple of versions behind and does not include any pre-release versions like 9.0.0

**Comment by postmodern** [comment]
You can install arbitrary versions via `ruby-install jruby X.Y.Z`. Also feel free to add newer versions to the [ruby-versions](https://github.com/postmodern/ruby-versions) repo. I will eventually add an `--update` option to automate this.

**Comment by timuckun** [comment]
I wasn't aware of the ruby-versions repo.

Thanks.
