### ISSUE TITLE
Install by sha1, sha256, or sha512

### ISSUE THREAD

**Issue by JuanitoFatas** [postmodern/ruby-install#205]
Hi @postmodern,

Since https://github.com/ruby/www.ruby-lang.org/pull/968 now replace md5 with sha256, do you have plans on adding shaN as an install option?

```
$ ruby-install --sha1 SHA1 ruby 2.3.4
$ ruby-install --sha256 SHA256 ruby 3.4.5
$ ruby-install --sha256 SHA512 ruby 4.5.6
```

Thanks for ruby-install!!!!!!

**Comment by havenwood** [comment]
There are actually already [options](https://github.com/postmodern/ruby-install/blob/59c02fbd12c92395ddea2397ed4545b758eef243/doc/man/ruby-install.1.md#options) for `--sha1`, `--sha256` and `--sha512` in addition to `--md5`. You can provide more than one of those flags to check more than one. For known versions ruby-install will try checking all four hash functions, see [checksums.sh](https://github.com/postmodern/ruby-install/blob/master/share/ruby-install/checksums.sh). All those checksums are collected in a common repository called [ruby-versions](https://github.com/postmodern/ruby-versions#readme).
