### ISSUE TITLE
Recommended improvement to the ruby-install command line interface

### ISSUE THREAD

**Issue by globalkeith** [postmodern/ruby-install#218]
I'm new to ruby-install, and very impressed, however I just tried to install a new ruby with `ruby-install 2.2.1` which resulted in `ruby-install: unsupported ruby: 2.2.1` - I quickly discovered my error from reading the readme on github, but it would be nice if the error message contained a helpful hint about what I might have done wrong and I wouldn't even need to leave the console to discover the solution. Many thanks for sharing your hard work.

**Comment by bronson** [comment]
I agree.  And the error message doesn't help.  `unsupported ruby: 2.2.1` shows that the command knows you're trying to install a ruby, so why would the solution be to specify `ruby 2.2.1`?

**Comment by postmodern** [comment]
I accidentally already implemented this in the ruby-versions branch. https://github.com/postmodern/ruby-install/blob/b33db550eea4fc1def8451979ea1b2df6fe149f9/share/ruby-install/ruby-install.sh#L71-L92

**Comment by bronson** [comment]
Very cool, looking great.  Does it make sense to try the branch?  Alpha quality, looking for feedback?

**Comment by postmodern** [comment]
Finished adding tests for the new code and everything is passing. Definitely looking for feedback on usability. I went with the simplest approach first of auto-downloading the files if they are missing, or if `--update` is specified.

**Comment by postmodern** [comment]
0.6.0 is now released. Happy `--latest`ing!

**Comment by bronson** [comment]
Allowing both `ruby-2.3` and `ruby 2.3` is excellent.  It like the original issue is still there though...  technically.

```
~$ ruby-install 2.3
!!! Unknown ruby: 2.3
~$ ruby-install ruby 2.3
>>> Installing ruby 2.3.0 into /Users/bronson/.rubies/ruby-2.3.0 ...
```

Using 0.6.0.

**Comment by havenwood** [comment]
@bronson See #44 for some discussion about why just a version isn't supported.

I wonder about just making the error message more helpful when the arguments start with a digit.

**Comment by bronson** [comment]
Ah, thanks.  That's good reading.

Agreed, a better error message would be great.
