### ISSUE TITLE
Verification fails for equal md5 checksums.

### ISSUE THREAD

**Issue by thegedge** [postmodern/ruby-install#226]
```
$ ruby-install ruby
>>> Downloading http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.bz2 into $HOME/src ...
>>> Verifying ruby-2.2.2.tar.bz2 ...
!!! Invalid md5 checksum for $HOME/src/ruby-2.2.2.tar.bz2
!!!   expected: af6eb4fa7247f1f7b2e19c8e6f3e3145
!!!   actual:   af6eb4fa7247f1f7b2e19c8e6f3e3145
!!! Verification of ruby-2.2.2.tar.bz2 failed!
```

My guess is trailing whitespace. Tested against HEAD on OSX 10.9.5.

**Comment by postmodern** [comment]
The `checksums.md5` in master has the correct number of spaces, so it must be the utility or our parsing of it's output:

    00000000  61 66 36 65 62 34 66 61  37 32 34 37 66 31 66 37  |af6eb4fa7247f1f7|
    00000010  62 32 65 31 39 63 38 65  36 66 33 65 33 31 34 35  |b2e19c8e6f3e3145|
    00000020  20 20 72 75 62 79 2d 32  2e 32 2e 32 2e 74 61 72  |  ruby-2.2.2.tar|
    00000030  2e 62 7a 32 0a                                    |.bz2.|

Although, we are attempting to [remove trailing whitespace](https://github.com/postmodern/ruby-install/blob/7901eb01f66bb345cdb80073bf9a99c768806285/share/ruby-install/checksums.sh#L50). Could you paste the output of `md5 $HOME/src/ruby-2.2.2.tar.bz2 | hexdump -C`?

**Comment by thegedge** [comment]
Output from `md5 -r ruby-2.2.2.tar.bz2 | hexdump -C` in `$HOME/src`:
```
00000000  61 66 36 65 62 34 66 61  37 32 34 37 66 31 66 37  |af6eb4fa7247f1f7|
00000010  62 32 65 31 39 63 38 65  36 66 33 65 33 31 34 35  |b2e19c8e6f3e3145|
00000020  20 72 75 62 79 2d 32 2e  32 2e 32 2e 74 61 72 2e  | ruby-2.2.2.tar.|
00000030  62 7a 32 0a                                       |bz2.|
00000034
```
Looks like there's only one space instead of two.

**Comment by postmodern** [comment]
Shouldn't be a problem since we do `echo -n "${output%% *}"`. Since I don't have an OS X system in front of me and I'm all out of ideas, pinging @havenwood.

**Comment by thegedge** [comment]
You're right, my bad. I always forget the `*` there is a glob-style pattern, not a regex :)

I investigated more and found the problem, which actually isn't exclusive to OSX: I have `GREP_OPTIONS="--color=always" in my environment, so you should pass `--color=never` [here](https://github.com/postmodern/ruby-install/blob/7901eb01f66bb345cdb80073bf9a99c768806285/share/ruby-install/checksums.sh#L24).

**Comment by postmodern** [comment]
From the man-page, it looks like we'll need to unset GREP_OPTIONS, GREP_COLOR and GREP_COLORS.

**Comment by thegedge** [comment]
Reinstalled at HEAD and everything is working a-o-k now. Thanks for the quick fix, @postmodern!

**Comment by postmodern** [comment]
Good to hear! Now have to figure out when to do a release.
