### ISSUE TITLE
!!! Compiling ruby 1.9.2-p330 failed!

### ISSUE THREAD

**Issue by lifeBalance** [postmodern/ruby-install#228]
I'm on Yosemite, trying to install **ruby 1.9.2-p330** by doing:

```
$ ruby-install -M https://ftp.ruby-lang.org/pub/ruby ruby 1.9.2-p330 -- CC=gcc-4.9
```

but I get the error pointed out in the title. What to do?

**Comment by havenwood** [comment]
Closing this issue since it's so old. If anyone runs into something similar, please visit us in the #chruby channel on Freenode.net IRC or start a new issue. Thanks!
