### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by boone** [postmodern/ruby-install#230]
I noticed that the [homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ruby-install.rb) for ruby-install uses the last release, which was October 2014.

Will there be future releases, or should the homebrew formula just point to master?

Thanks!

**Comment by dentarg** [comment]
Would be nice with a new release because 0.5.0 does not use [https for cache.ruby-lang.org](https://github.com/postmodern/ruby-install/commit/9e97cc901f961b3d7dcc7a7ccea2153a9a39b395)

**Comment by postmodern** [comment]
Yeah about that. We have some experimental caching support in the [cache](https://github.com/postmodern/ruby-install/tree/cache) branch. @havenwood has been testing it and it seems to work. However, we need more tests before I can feel safe about merging it. I really want to include caching support in 0.5.0.

**Comment by boone** [comment]
@postmodern perhaps you could release 0.5.1 with the current master and 0.6.0 when the cache branch is merged?

**Comment by ches** [comment]
Seems like a release just for fresh suggested Ruby versions would be a good idea, if nothing else—I just finally upgraded a Mac to Yosemite and had one build headache after another with versions baked into ruby-install 0.5.0, installed by default from Homebrew. After a `brew rm ruby-install && brew install ruby-install --HEAD` everything was smooth and pain-free on the newer Rubies. I was helping a new developer alongside me get an environment set up and advocating my preference for ruby-install, and it didn't make a nice first impression :cry:

**Comment by postmodern** [comment]
I would rather we just do the work of reviewing the caching branch, that way we don't have to release new versions just for new rubies.

**Comment by mhenrixon** [comment]
Any idea on when a new release might happen?

```
ruby-install jruby-9.0.0.0
ruby-install: unsupported ruby: jruby-9.0.0.0
```

**Comment by ches** [comment]
@postmodern That's reasonable—is that branch to a point where you or @havenwood is ready to open a PR, to encourage others to review and test? A PR would be helpful to provide explanation of the branch's intent for the lesser-informed to quickly understand what we're looking at and how to test :smile:

**Comment by postmodern** [comment]
@ches basically [parse_ruby_version](https://github.com/postmodern/ruby-install/blob/e17d673f9d0bb60ae9905ca718ef10eb0e82c117/share/ruby-install/ruby-install.sh#L410-L434) just needs unit-tests. That function checks if the version is already known, if not, updates the versions/checksums, then attempts to resolve the version.

**Comment by postmodern** [comment]
I refactored the code and have a working-ish prototype in the [ruby-versions](https://github.com/postmodern/ruby-install/tree/ruby-versions) branch. It will auto-download versions/checksums files on first run and will update them if `--update` is specified. I just need to fix existing tests and write more tests for the new functionality, then we can release 0.6.0.
