### ISSUE TITLE
Compile 1.8.7 on OS X 10.10

### ISSUE THREAD

**Issue by jlecour** [postmodern/ruby-install#231]
Hi,

It's killing me to ask about this, since 1.8 is supposed to be 6ft under. The thing is, I'm trying to kind of maintain an old project that can't run on 1.9+ and I don't find a way to recompile Ruby 1.8.7 on my Mac.

Is there still a way to do this, even if it has to be done manually for some parts ?

I can find my way in a terminal, but I know nothing about compilation…

Thanks.

PS : writing this I've noticed that there is a precompiled Homebrew version of `ruby187` but it's full of symlinks and it shares its gems, site_ruby… with the global ruby, which obviously doesn't work.

**Comment by jlecour** [comment]
Here is the package and my issue : 

https://github.com/Homebrew/homebrew-versions/issues/962

**Comment by postmodern** [comment]
You pretty much have to manually compile Ruby 1.8.7 with an older version of gcc, openssl, etc. I would suggest using a legacy Ubuntu VM. There is also the [backports](https://rubygems.org/gems/backports) gem which helps with porting to 1.9.
