### ISSUE TITLE
ruby-install installs ruby version without ruby.h

### ISSUE THREAD

**Issue by dmoran-epages** [postmodern/ruby-install#234]
Hello.

If you install a ruby version using ruby-install everything works fine.
If you then install rails as a gem, it will fail complaining that it cant find files like "ruby.h"
One can install these via the os package manager, but this will almost certainly be  a version mismatch.. the version of my ruby-devel is 2.1 but I just installed ruby 2.2.3.

see https://github.com/postmodern/chruby/issues/349

Shouldn't the ruby version installed by ruby-install come with its own copy of any files like ruby.h (in the correct versions) it needs (to install gems like rails)??

Thanks in Advance.

**Comment by dayer4b** [comment]
+1

**Comment by postmodern** [comment]
Was an issue with using `sudo gem install` which runs as root using system ruby, instead of your current selected ruby. This is due to `sudo` filtering out sensitive environment variables (ex: `$PATH`) for security reasons.
