### ISSUE TITLE
Please upgrade version for brew and have a way to fetch the latest versions

### ISSUE THREAD

**Issue by timuckun** [postmodern/ruby-install#235]
Just a feature request.

Thanks.

**Comment by havenwood** [comment]
For now you can use the `brew reinstall ruby-install --HEAD` command to update to the latest master branch of ruby-install. The [cache branch](https://github.com/postmodern/ruby-install/tree/cache) supports fetching the latest versions when outdated. If you're interested in testing the cache branch any feedback is appreciated. I look forward to it in the 0.6.0 release! Closing as a duplicate of #230.
