### ISSUE TITLE
`--cleanup` not working at all

### ISSUE THREAD

**Issue by vitorgalvao** [postmodern/ruby-install#236]
`--cleanup` doesn’t work at all, for me. I don’t even see any message pertaining to it (though the source seems to suggest there should be some).

The command I’m using is

```bash
latest_ruby=$(curl --silent 'https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/stable.txt' | tail -1)
ruby-install --cleanup ruby "${latest_ruby}"
```

Also tried moving `--cleanup` to the end of that. Same result. If I do a typo (like `--cleanuo`) it does say it doesn’t recognise the command, so it does indeed recognise `--cleanup`, it just isn’t doing it.

---

`ruby-install` `0.5.0`, installed via `homebrew`.
OS X `10.10` and `10.11`.

**Comment by havenwood** [comment]
I'm not able to reproduce this with ruby-install 0.5.0 on OS X with bash 3/4 or zsh.

Double check that the downloaded Ruby archive isn't getting deleted after successful installation? Is the output at the end similar to the following?:
```sh
>>> Removing ~/src/ruby-2.2.3.tar.bz2 ...
>>> Removing ~/src/ruby-2.2.3 ...
>>> Successfully installed ruby 2.2.3 into ~/.rubies/ruby-2.2.3
```

**Comment by vitorgalvao** [comment]
Ah, something occurred to me (was going to specify that in the top post but forgot).

I slightly misunderstood the option. I was under the impression the `src` dir would be removed, but that appears to not be the case. Why not, though? I understand you might not want to blindly delete the directory in case it already existed, but it seems to me a `cleanup` option should indeed get rid of it if it wasn’t there before. I can see a few options:

+ `rmdir` it. This way, the directory will only be gone if it is empty.
+ When first creating the directory, check if it exists. If it doesn’t, make a note of it and delete it after everything is done (only if `--cleanup` was given, naturally).

If any of those sounds good to you, I’d be glad to look through the code and submit a PR. The first solution is easy enough and already found where to do it, whereas for the second I’ll have to read the code a bit more.

If you want the second solution implemented it might take me a few weeks since I currently do not have my computer (so I’m limited to the web interface).

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/postmodern/ruby-install/issues/239 (since it is specific to the implementation of the feature).
