### ISSUE TITLE
Ruby 2.2.3 Download Failing, '--no-check-certificate' not working

### ISSUE THREAD

**Issue by igolden** [postmodern/ruby-install#237]
Hi,

First off, love using ruby-install and chruby to manage my rubies. I feel like it's the most lightweight, non convoluted way to manage rubies. So thanks for all you awesome work on this gem!

But when I'm trying to download the latest stable version of Ruby (2.2.3), I get the following error consistently.

>>> Downloading https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2 into /Users/denverwebco/src ...
--2015-10-10 08:13:41--  https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2
Resolving cache.ruby-lang.org... 199.27.79.68
Connecting to cache.ruby-lang.org|199.27.79.68|:443... connected.
ERROR: cannot verify cache.ruby-lang.org's certificate, issued by 'CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE':
  Issued certificate has expired.
To connect to cache.ruby-lang.org insecurely, use `--no-check-certificate'.
!!! Download of https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2 failed!

I've tried a bunch of stuff, can't get around it. I could potentially try other download alternatives, but I like ruby-install. Any thoughts? You seen this before?

Thanks in advance,
Ian

**Comment by igolden** [comment]
Nevermind, I fixed this by reinstalling ruby-install with homebrew. I think I had installed it using the following method for some reason:

'brew install ruby-install --HEAD'

I just uninstalled, and reinstalled normally.

'brew uninstall ruby-install'
'brew install ruby-install'

**Comment by fingolfin** [comment]
I have the same issue, I guess it is because of 9e97cc901f961b3d7dcc7a7ccea2153a9a39b395 -- so perhaps this should be reopened?
