### ISSUE TITLE
`--cleanup` should remove `src` directory

### ISSUE THREAD

**Issue by vitorgalvao** [postmodern/ruby-install#239]
From https://github.com/postmodern/ruby-install/issues/236#issuecomment-146638902, regarding `cleanup`:

I was under the impression the `src` dir would be removed, but that appears to not be the case. Why not, though? I understand you might not want to blindly delete the directory in case it already existed, but it seems to me a `cleanup` option should indeed get rid of it if it wasn’t there before. I can see a few options:
- `rmdir` it. This way, the directory will only be gone if it is empty.
- When first creating the directory, check if it already existed. If it didn’t, make a note of it and delete it after everything is done (only if `--cleanup` was given, naturally).

If any of those sounds good to you, I’d be glad to look through the code and submit a PR. The first solution is easy enough and I already found where to do it, whereas for the second I’ll have to read the code a bit more.

**Comment by postmodern** [comment]
Attempting to `rmdir` the directory sounds like a good idea. Maybe add a `[[ -n "$(ls -A src)" ]]` check first? Although, I'm considering eventually downloading/extracting into `~/.cache/ruby-install/`.

**Comment by vitorgalvao** [comment]
> Maybe add a `[[ -n "$(ls -A src)" ]]` check first?

No need. `rmdir` only deletes empty directories. We could `[[ -e 'src' ]]` to make sure it exists, though, but there are other operations done on it right before, so there’s really no need for it.

> Although, I'm considering eventually downloading/extracting into `~/.cache/ruby-install/`.

I currently [download it to a temporary directory made on the fly](https://github.com/vitorgalvao/dotfiles/blob/22d6ace844688cd9d63033209b28f1b4c172753c/scripts/01_environments.sh#L20).

Either way, first draft for review at #251.

**Comment by justanton** [comment]
noob comment on that: 
after done installing Ruby with `ruby-install`, is that ok to remove ~/src directory? I assume these are source files needed for installation only, and not for Ruby to work afterwards.

**Comment by vitorgalvao** [comment]
@justanton Yes, it’s OK to delete it.

**Comment by justanton** [comment]
Thank you @vitorgalvao !

**Comment by postmodern** [comment]
Minor note: if you ever have to debug ruby with `gdb`, keeping the source allows gdb to print the source code lines when stepping through `ruby`.

**Comment by vitorgalvao** [comment]
Closing for lack of interest, as I don’t think it’ll ever be merged and I have long stopped using the tool.

Closing as part of personal cleanup of old PRs and issues. I don’t think this will ever be fixed in the suggested manner and have long stopped using the tool, so no point to inflating the number of issues.
