### ISSUE TITLE
Fails without bzip2

### ISSUE THREAD

**Issue by sheldonh** [postmodern/ruby-install#241]
ruby-install fails on systems without bzip2 installed:

```
>>> Verifying ruby-2.2.3.tar.bz2 ...
*** No md5 checksum for /usr/local/src/ruby-2.2.3.tar.bz2
*** No sha1 checksum for /usr/local/src/ruby-2.2.3.tar.bz2
*** No sha256 checksum for /usr/local/src/ruby-2.2.3.tar.bz2
*** No sha512 checksum for /usr/local/src/ruby-2.2.3.tar.bz2
>>> Extracting ruby-2.2.3.tar.bz2 to /usr/local/src/ruby-2.2.3 ...
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
!!! Unpacking of ruby-2.2.3.tar.bz2 failed!
```

I think bzip2 should be added to dependencies?

**Comment by postmodern** [comment]
It is listed as a requirement in the README. How did you install ruby-install?

**Comment by sheldonh** [comment]
I used an Ansible role that was written for Ubuntu, where you get bzip2 out of the box. It's not a problem if you're happy with it being a documentated manual dependency. I just noticed the lengths the script goes to, to install dependencies, and assumed it must be an oversight, without checking the README.
