### ISSUE TITLE
ruby-install ruby 2.2 failing to download?

### ISSUE THREAD

**Issue by enxebre** [postmodern/ruby-install#243]
When ``` ruby-install ruby 2.2 ```
I got:

Warning: openssl-1.0.2d_1 already installed
Warning: readline-6.3.8 already installed
Warning: libyaml-0.1.6_1 already installed
Warning: gdbm-1.11 already installed
Warning: libffi-3.0.13 already installed
>>> Downloading http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.tar.bz2 into /Users/Enxebre/src ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
!!! Download of http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.tar.bz2 failed!

Wonder if anyone is able to reproduce this.
Thanks.

**Comment by wallies** [comment]
i get the same on brand new mac with brew. i was wondering whether it was based on a two number thing but this works ruby-install ruby 2.0, 2.1 etc. but not with the newest 2.2. Tested with master and 0.6 branch and it now works. So im thinking it has something to do with ruby-versions

**Comment by ilikepi** [comment]
The stable version of ruby-install currently in Homebrew is out of date.  See the work-around provided in [this comment](https://github.com/postmodern/ruby-install/issues/235#issuecomment-146390633) on a similar issue.

This was also reported in #230.

**Comment by postmodern** [comment]
ruby-install 0.6.0 has been released and is now available in homebrew. What's different in this ruby-install is it will auto-download the version/checksum files on first run, or if the `--latest` option is given.
