### ISSUE TITLE
Use https by default when downloading source 

### ISSUE THREAD

**Issue by Immortalin** [postmodern/ruby-install#247]
Currently it downloads from `http://cache.ruby-lang.org/pub/ruby/<version>` etc., it would be more secure to use the https version by default instead.

**Comment by aprescott** [comment]
The latest `master` commit [seems to use HTTPS](https://github.com/postmodern/ruby-install/blob/9c08e56c799532acfced926eb8adc70efbbcce3f/share/ruby-install/ruby/functions.sh#L6):

```shell
ruby_mirror="${ruby_mirror:-https://cache.ruby-lang.org/pub/ruby}"
```

Maybe you're seeing this on an older version of ruby-install?

**Comment by postmodern** [comment]
Already fixed. Just need time to do a release.

**Comment by aprescott** [comment]
Looks like this made it into the 0.6.0 release. Thanks @postmodern!
