### ISSUE TITLE
ruby-install --latest  "unrecognized" and ruby -v disconnect

### ISSUE THREAD

**Issue by MtnBiker** [postmodern/ruby-install#252]
From the terminal. Two problems. --latest doesn't work. Latest version earlier than what I have. On El Capitan. Haven't installed any Rubies with ruby-install.
~  $ ruby-install --latest
ruby-install: unrecognized option --latest
~  $ ruby-install
Latest ruby versions:
  ruby:
    1.9.3-p547
    2.0.0-p576
    2.1.3
  jruby:
    1.7.16
  rbx:
    2.2.10
  maglev:
    1.0.0
  mruby:
    1.0.0
~  $ ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by havenwood** [comment]
It seems you're not using the latest ruby-install 0.6.0, which adds support for the `--latest` option.

Check your ruby-install version?
```sh
ruby-install --version
```

**Comment by MtnBiker** [comment]
$ ruby-install --version
ruby-install: 0.5.0
I just installed ruby-install using 'brew install ruby-install', so brew's not up to date. And that's a recommended method to install.
brew install ruby-install --HEAD comes up with 0.5.0. 
I can it fixed/closed when the ReadMe is updated to reflect this problem.
Thanks for answering. Guess I can use wget to install, but I don't need that many things to keep track of.

**Comment by MtnBiker** [comment]
Posted too quickly. brew update, brew upgrade got me to 0.6.0.
And ruby-install --version is now consistent.
Although it shouldn't be necessary, maybe a caveat about brew update, brew upgrade could be added to the ReadMe. 

I guess I need to know why brew install doesn't install the latest version, seems like brew needs fixing, but that's another issue.
