### ISSUE TITLE
After installing Ruby 2.0.0 my system cannot "see" or use it.

### ISSUE THREAD

**Issue by im-grey** [postmodern/ruby-install#257]
This is in Trisquel 7.

```
...
...
...
>>> Successfully installed ruby 2.0.0-p648 into /home/grey/.rubies/ruby-2.0.0-p648
grey@x60:~$ ruby -v
bash: ruby: command not found
```

**Comment by postmodern** [comment]
Use [chruby]() to see/use rubies installed into `~/.rubies/` or `/opt/rubies.` Or install the ruby globally using the `--system` flag.

**Comment by im-grey** [comment]
I tried this but it left me with the following error.
````
make: *** [do-install-all] Error 1
!!! Installation of ruby 2.0.0-p648 failed!
grey@x60:~$
````


Full - http://pastebin.com/4ka4QTeb

**Comment by postmodern** [comment]
Forgot to mention `--system` requires root privs. `sudo ruby-install --system ruby 2.0` should do the trick.

**Comment by im-grey** [comment]
What if I already am, and was, doing it with ```sudo```?

**Comment by postmodern** [comment]
Can you paste the full ruby-install command?

**Comment by im-grey** [comment]
So, I was trying something different after my last comment. The original command was 
````sudo ruby-install --system ruby 2.0.0-p648````
Which failed with the above error. But then I tried 
````sudo ruby-install --system --latest ruby````
Which actually worked!
````
>>> Successfully installed ruby 2.3.0 into /usr/local
grey@x60:~$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
grey@x60:~$ gem -v
2.5.1
````

I wonder why that is?

**Comment by postmodern** [comment]
Does `sudo ruby-install --system ruby 2.0.0-p648` continue to fail with the "Permission denied error" or a different error?
