### ISSUE TITLE
Downloading latest versions fails

### ISSUE THREAD

**Issue by xijo** [postmodern/ruby-install#261]
Hi,

on my ubuntu machine with `ruby-install` version `0.6.0` I get the following error:

```
$ ruby-install
>>> Downloading latest ruby versions ...
!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt to /home/apps/.cache/ruby-install/ruby/versions.txt!
>>> Downloading latest jruby versions ...
!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/jruby/versions.txt to /home/apps/.cache/ruby-install/jruby/versions.txt!
>>> Downloading latest rbx versions ...
!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/rubinius/versions.txt to /home/apps/.cache/ruby-install/rbx/versions.txt!
>>> Downloading latest maglev versions ...
!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/maglev/versions.txt to /home/apps/.cache/ruby-install/maglev/versions.txt!
>>> Downloading latest mruby versions ...
!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/mruby/versions.txt to /home/apps/.cache/ruby-install/mruby/versions.txt!
Stable ruby versions:
  ruby:
cat: /home/apps/.cache/ruby-install/ruby/stable.txt: No such file or directory
  jruby:
cat: /home/apps/.cache/ruby-install/jruby/stable.txt: No such file or directory
  rbx:
cat: /home/apps/.cache/ruby-install/rbx/stable.txt: No such file or directory
  maglev:
cat: /home/apps/.cache/ruby-install/maglev/stable.txt: No such file or directory
  mruby:
cat: /home/apps/.cache/ruby-install/mruby/stable.txt: No such file or directory
```

Getting the files manually via curl works as expected. Any ideas how to continue debugging?

Thanks in advance,
Jo

**Comment by postmodern** [comment]
First, I would check the permissions of `/home/apps/.cache/ruby-install/`. Also is this a one-time failure, intermittent or reproducible? Additionally, you could test the full `curl`/`wget` commands:

    wget -c -O "/home/apps/.cache/ruby-install/ruby/versions.txt.part" "https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt"
    curl -f -L -C - -o "/home/apps/.cache/ruby-install/ruby/versions.txt.part" "https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt"

It could be an issue with a newer version of `curl`/`wget`, but I'm guessing it's permissions related.

**Comment by eurojet** [comment]
I think there is a problem with the server certifcate. this workaround for "wget" works for me:
file:ruby-install-0.6.0/share/ruby-install/util.sh
in function download() change the line:
		wget) wget -c -O "$dest.part" "$url" || return $?         ;; 
for this one:
		wget) wget --no-check-certificate -c -O "$dest.part" "$url" || return $?         ;; 

I hope this works for you.

**Comment by postmodern** [comment]
@eurojet you most certainly want to check the certificate, otherwise you could be MITMed. Could you paste the full details of the certificate you're getting back for https://raw.githubusercontent.com/? The certificate I get back is registered for `www.github.com`, but includes `raw.githubusercontent.com` in the Subject Alternative Name section.

**Comment by eurojet** [comment]
Don't worry about it.  This is a problem with old versions (1.12) of wget, and the workaround is the option "--no-check-certificate". it works fine with new versions (1.16).

Congratulations for your excellent work!!! It is very usefull for me.

Best regards.

**Comment by anamewing** [comment]
Mayby the install script should check version of `wget`, if `wget` is too old, the script should consider using `curl`.

I can reproduce this issue with `wget 1.12` on Centos 6.5, with `ruby-install 0.6.0`.

**Comment by postmodern** [comment]
I will update the dependencies in the README and packages.
