### ISSUE TITLE
readline support not working?

### ISSUE THREAD

**Issue by mperham** [postmodern/ruby-install#263]
I'm running 0.6.0 on El Capitan.  I've run `brew install readline` but when I ruby-install the latest 2.3, my irb does not support history.  This note about keg-only looks ominous, is there a way to make this Just Work™ with ruby-install so the user doesn't need to symlink anything or worry about this?

```
$ brew info readline
readline: stable 6.3.8 (bottled) [keg-only]
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/usr/local/Cellar/readline/6.3.8 (40 files, 2M)
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/readline.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.


Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include
```

**Comment by postmodern** [comment]
ruby-install already [explicitly passes in the `brew --prefix` values for all dependencies](https://github.com/postmodern/ruby-install/blob/bb5328a6cf28bf1dbe21cc60d0de30e53afea1a1/share/ruby-install/ruby/functions.sh#L24-L32). What does `brew --prefix readline` return? Or is this another issue where the version of libreadline is newer than what ruby currently supports?

**Comment by mperham** [comment]
```
$ brew --prefix readline
/usr/local/opt/readline
$ brew info readline
readline: stable 6.3.8 (bottled) [keg-only]
```

**Comment by postmodern** [comment]
@mperham could you try compiling the ruby manually with `--with-opt-dir=$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm)`?

**Comment by mperham** [comment]
Like so? `ruby-install ruby -- --with-opt-dir=$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm)`

**Comment by postmodern** [comment]
Sorry meant:

    ./configure --with-opt-dir=$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm) --prefix=$HOME/.rubies/ruby-....
    make
    make install

**Comment by mperham** [comment]
If I run the first two commands and then `bin/irb` to run the built binary, history works as expected.

**Comment by mperham** [comment]
Hold on, now I can't reproduce the history not working.  Up arrow is working for me.  Maybe I somehow activated the system Ruby.  Will reopen if I can reproduce it again.

**Comment by espen** [comment]
I think I'm having the same issue. Suddenly after installing 2.7.0 I lost irb history. It works with 2.6.4 (even after reinstall of both versions). On 2.7.0 IRB will write to history but not read from it.

**Comment by JamesChevalier** [comment]
Yeah, I've lost irb history with 2.7.1 in the same way - the history is written but not read.

```
$ brew --prefix readline
/usr/local/opt/readline
$ which readline
$
```

I've tried reinstalling a number of packages that are mentioned in the output of `ruby-install ruby 2.7.1`:
automake bison openssl@1.1 readline libyaml gdbm libffi

I'm unsure where to run this command, or what the rest of it is (it's chopped off with `...`):
`./configure --with-opt-dir=$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm) --prefix=$HOME/.rubies/ruby-....`

I _don't_ have this issue in the ruby:2.7.1-alpine docker image.

Let me know if there's any other info that may be helpful.
