### ISSUE TITLE
Makefiles `all` target assumes a git repository

### ISSUE THREAD

**Issue by baccenfutter** [postmodern/ruby-install#270]
Build tools (such as the `ark` cookbook) will run the classic `./configure` + `make` + `make install` build-chain.

The installation routine of ruby-install requires only `make install` to be run, not `make`.

However, when `make` is run (without a target), the Makefile executes at least one git command, which fails when `ruby-install` was downloaded as tarball (does not contain the .git subfolder).

I think, ruby install should support the entire classic build-chain (e.g. configure+make+make install), even if there is no .git folder present.

I suggest either to rearrange targets, so git commands are only executed on explicit targets (e.g. make pkg) or the Makefile should check if the .git folder is present before executing git commands.

**Comment by postmodern** [comment]
I changed `all` to be a no-op in 4f2296fc97caede365e230ed1fa75364afcfee46.
