### ISSUE TITLE
Add bzip2 to dependency check

### ISSUE THREAD

**Issue by expit** [postmodern/ruby-install#273]
ruby-installer does not check if there is bzip2 binary on the system.
On Centos 7 there is no bzip2 package in minimal installation (probably the very same issue will be on RedHat, I don't know if any other minimal system comes without bzip2).
Due to lack of bzip2 following error occurs after downloading package:

> > > Verifying ruby-2.3.1.tar.bz2 ...
> > > Extracting ruby-2.3.1.tar.bz2 to /usr/local/src/ruby-2.3.1 ...
> > > tar (child): bzip2: Cannot exec: No such file or directory
> > > tar (child): Error is not recoverable: exiting now
> > > tar: Child returned status 2
> > > tar: Error is not recoverable: exiting now
> > > !!! Unpacking of ruby-2.3.1.tar.bz2 failed!

**Comment by postmodern** [comment]
This could be solved by installing ruby-install via an rpm. We have an rpm [spec file](https://github.com/postmodern/ruby-install/blob/master/rpm/ruby-install.spec) in the repo, and another user has created [COPR packages](https://copr.fedorainfracloud.org/coprs/nwallace/ruby-tools/).

**Comment by markovanderpuil** [comment]
I have the exact same issue. Also as of now, there is no rpm for ruby-install in either Centos or Epel repos.

**Comment by postmodern** [comment]
I've since created an official [COPR repo for ruby-install](https://copr.fedorainfracloud.org/coprs/postmodern/ruby-install/).

**Comment by markovanderpuil** [comment]
Thanks, that's awesome, however Centos 7 & RHEL 7 do not support copr yet on neither dnf nor yum.

The Ruby install installation actually checks for dependancies and then installs them. Can we check for bzip2 or can we use something else like gzip, which is available on minimal installs?

**Comment by alyssais** [comment]
:+1: the COPR repo hasn't been updated for recent releases of Fedora, so isn't really a great option.

**Comment by postmodern** [comment]
I tried refreshing the build for another version of Fedora, but it broke for some reason. I asked in one of the COPR channels but didn't get a response.

Should we add specialized installation instructions for RedHat based distros (ex:`dnf install bzip2 && sudo make install`) to the README? Or should we add bzip to the `dependency.txt` files for all package managers?

**Comment by markovanderpuil** [comment]
How about both?

**Comment by paul** [comment]
@franklinyu Yeah, sorry, I hate it when packages are just abandoned like that. I switched to PopOS to try it out when it came out, but I want to switch back to Fedora at some point, just haven't had the time.

**Comment by rb83** [comment]
Just bumped into this as well.

**Comment by postmodern** [comment]
This will be resolved in the 0.8.0 release. We're switching to downloading the `.tar.xz` ruby release and making xz-utils an explicit dependency (excluding macOS and FreeBSD, which has it built-in to the base system). See the [use_tar_xz_for_ruby](https://github.com/postmodern/ruby-install/compare/0.8.0...use_tar_xz_for_ruby) for more details.
