### ISSUE TITLE
install latest ruby? (2.3.1)

### ISSUE THREAD

**Issue by benlieb** [postmodern/ruby-install#275]
Is there a step I need to do do have ruby-install have the ability install the latest?

Also:

http://stackoverflow.com/questions/37648055/ruby-install-to-install-latest-ruby

**Comment by postmodern** [comment]
Make sure your running ruby-install version >= 0.6.0. From `ruby-install --help`

    	-L, --latest		Downloads the latest ruby versions and checksums

So to update and install the latest stable version of ruby, you'd run:

    ruby-install --latest ruby

That's it!

**Comment by nengxu** [comment]
@postmodern This is confusing. The latest ruby is 2.3.1. So according to the document, the following command should install the latest stable version:

ruby-install ruby

How can ruby-install still assume that 2.3.0 is the latest stable version?

Is there some definition file where the latest stable version is defined? If so, how is this file updated? Thanks.

**Comment by havenwood** [comment]
@nengxu Instead of `ruby-install ruby` use `ruby-install --latest ruby` to download the latest versions and checksums from [ruby-versions](https://github.com/postmodern/ruby-versions#readme) and install the latest Ruby.

**Comment by nengxu** [comment]
@havenwood Thanks.
