### ISSUE TITLE
Fedora 24 may need explicit bison dnf dependency

### ISSUE THREAD

**Issue by sebn** [postmodern/ruby-install#277]
Installing ruby 2.2.1 on Fedora 24 works fine.
But when trying to run `rails console` on some project, `require 'ripper'` fails.
Looking at the ruby build log, it seems `ripper` was not built because bison was not found.
Running `dnf install bison` installs it, which means it wasn't installed by `ruby-install` as a dnf dependency.
My guess is that it was pulled as a transitive dependency on Fedora 23, but not anymore on Fedora 24, but I could not find which package was depending on it.

(I'm really sorry for the low-quality report, but I'm lacking time right now, and I didn't want to forget this one. Also I'd hope it may help somebody else. I will try to reproduce the issue in a few days I hope.)

**Comment by postmodern** [comment]
Good catch. Annoying that MRI does not have an explicit list of build dependencies.
