### ISSUE TITLE
rubinius install tries to system install mri

### ISSUE THREAD

**Issue by burningTyger** [postmodern/ruby-install#288]
I have 2.3.3. installed through ruby-install and now I'm trying to add rbx. Upon `ruby-install rbx 3.69` ruby-install tries to install 2.3.3 again through the system package manager. Is this the supposed behaviour?

I'm on Arch Linux w/o a system ruby installed.
I'm building from source now, the actual missing dependency was llvm.

**Comment by postmodern** [comment]
This is intentional. ruby-install installs MRI from the package manager along with the other Rubinius build dependencies. We use the system's Ruby for consistency.

**Comment by burningTyger** [comment]
ok, thanks.

not just for the quick answer but also for chruby and the installer. Works painless and is just a great piece of software. :+1:
