### ISSUE TITLE
Readline failed on FreeBSD 11

### ISSUE THREAD

**Issue by papilip** [postmodern/ruby-install#299]
Hello All,

After install a new FreeBSD 11 server, ruby compile but without **readline** ```irb``` and ```rails console``` sucks

After some internet search i found a solution: 
* install readline ```sudo pkg install readline```
* compile ruby with specific dir ```ruby-install ruby 2.4.1 -- --with-readline-dir=/usr/local/```

**Comment by havenwood** [comment]
There's [a branch with pkg support](https://github.com/postmodern/ruby-install/tree/pkg) from a few years ago that hasn't made it into master yet. The deps that would have been installed via pkg for ruby are: `openssl readline libyaml gdbm libffi`

**Comment by postmodern** [comment]
If there's interest, let's dig up the pkg branch and test it out in a VM.

**Comment by papilip** [comment]
Thank you very much, I will test this branch and will come back give you the result

**Comment by havenwood** [comment]
I opened PR #300 with an updated patch for pkg support.
