### ISSUE TITLE
problem compil 2.2.8 on kali rolling

### ISSUE THREAD

**Issue by lacroutelacroute** [postmodern/ruby-install#304]
hey admin

i have problem to compil ruby 2.2.8 on kali rolling
already compil 2.2.7

my trace
Generating RDoc documentation
Parsing sources...
100% [967/967]  vsnprintf.c                                                 

Generating RI format into /usr/local/src/ruby-2.2.8/.ext/rdoc...
Marshal.dump reentered at marshal_dump
/usr/local/src/ruby-2.2.8/lib/rdoc/store.rb:865:in `dump'
	/usr/local/src/ruby-2.2.8/lib/rdoc/store.rb:865:in `save_class'
	/usr/local/src/ruby-2.2.8/lib/rdoc/store.rb:749:in `block in save'
	/usr/local/src/ruby-2.2.8/lib/rdoc/store.rb:748:in `each'
	/usr/local/src/ruby-2.2.8/lib/rdoc/store.rb:748:in `save'
	/usr/local/src/ruby-2.2.8/lib/rdoc/generator/ri.rb:26:in `generate'
	/usr/local/src/ruby-2.2.8/lib/rdoc/rdoc.rb:530:in `block in generate'
	/usr/local/src/ruby-2.2.8/lib/rdoc/rdoc.rb:525:in `chdir'
	/usr/local/src/ruby-2.2.8/lib/rdoc/rdoc.rb:525:in `generate'
	/usr/local/src/ruby-2.2.8/lib/rdoc/rdoc.rb:508:in `document'
	./bin/rdoc:20:in `<main>'

uncommon.mk:427 : la recette pour la cible « rdoc » a échouée
make: *** [rdoc] Erreur 1
!!! Compiling ruby 2.2.8 failed!
:/opt/ruby-install/ruby-install$ 

my command 
sudo ./bin/ruby-install ruby 2.2.8 --no-install-deps

other new version of ruby compil without problem

**Comment by lacroutelacroute** [comment]
install of 2.2.8 work with ruby-build

after past two command
export RUBY_CONFIGURE_OPTS="--disable-install-rdoc"
export RUBY_CONFIGURE_OPTS="--disable-install-doc"

**Comment by lacroutelacroute** [comment]
I just tried to recompile 2.2.7 without success

**Comment by lacroutelacroute** [comment]
manual compil and install work with this options
./configure  --disable-install-doc  --disable-install-rdoc  --prefix=/opt/rubies/ruby-2.2.8
make
make install

**Comment by eins78** [comment]
@lacroutelacroute If you need to pass flags/opts to the build process, put them at the end of the command, after a `--`.

So your command should be: 
`sudo ./bin/ruby-install ruby 2.2.8 --no-install-deps -- --disable-install-rdoc --disable-install-do`

**Comment by lacroutelacroute** [comment]
work fine

**Comment by eregon** [comment]
`ruby-install ruby 2.2.9 -- --disable-install-rdoc --disable-install-ri` indeed fixes for me as well.

**Comment by eregon** [comment]
FWIW, same for 2.2.10:
```
Generating RI format into /home/eregon/src/ruby-2.2.10/.ext/rdoc...
Marshal.dump reentered at marshal_dump
/home/eregon/src/ruby-2.2.10/lib/rdoc/store.rb:865:in `dump'
```
