### ISSUE TITLE
Support for openssl md5 was dropped, any reason why?

### ISSUE THREAD

**Issue by yb66** [postmodern/ruby-install#308]
Hi,

The README and Changlog both say there's support for `openssl md5` but the line with that check appears to have been removed. Any reason? I can"t find an issue/commit message that specifies why.

Regards,
iain

**Comment by havenwood** [comment]
There [is support for md5](https://github.com/postmodern/ruby-install/blob/master/share/ruby-install/checksums.sh) when you have the `md5` or `md5sum` commands available. (If that's what you mean?) If appropriate checksum commands are found, md5, sha1, sha256 and sha512 are all checked.

**Comment by havenwood** [comment]
Ah, nevermind - I see what you're asking.

**Comment by yb66** [comment]
@havenwood Sorry if it wasn't clear, I'd have included links to the commits with the changes but with all the structural changes over the years I really wasn't clear what had gone where and thought it best to just ask.

**Comment by havenwood** [comment]
I'd forgotten but `openssl md5` support [was added in this commit](https://github.com/postmodern/ruby-install/commit/82f9dbf08e62ec69a9bb847653a06f05f95f9a52). The last artifact of it in the code was [removed in this commit](https://github.com/postmodern/ruby-install/commit/cb61cce7189775fc864a6205014aa052c8ecffae#diff-b20e3eb34ab9de84e2ca343298ac8e29). Good question!

**Comment by yb66** [comment]
@havenwood If there's no philosophical reason against it then the pull request is there if needed. 

And if anyone wants to clear up my ignorance and tell me how to run the tests that would be nice too! :)

iain

**Comment by postmodern** [comment]
If memory serves me correctly, it was because Apple decided to replace `libopenssl` with a more up-to-date BSD `libssl` alternative after HeartBleed, and the other many openssl bugs. @havenwood correct me if I'm wrong, since I'm not a macOS user.

**Comment by havenwood** [comment]
@postmodern you're right—that refreshes my recollection. When macOS went to LibreSSL the command line tool became incompatible so we had no portable way to check md5 with `openssl` anymore.
