### ISSUE TITLE
I tried to install Ruby 2.3.4 and I have Ruby 2.3.1 

### ISSUE THREAD

**Issue by javiereaw** [postmodern/ruby-install#312]
I tried to install Ruby 2.3.4 and I have Ruby 2.3.1 
Ubuntu 16.04 

I used:

sudo apt-get install -y make
wget -O ruby-install-0.6.1.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.1.tar.gz

tar -xzvf ruby-install-0.6.1.tar.gz

cd ruby-install-0.6.1/

sudo make install

ruby-install ruby 2.3.4

sudo apt-get install -y gems

sudo apt-get install -y rubygems

ruby -v

xxxxx@localhost:~/ruby-install-0.6.1# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by oharace** [comment]
`ruby -v` is showing the global ruby version that is being used. You installed 2.3.4, but didn't switch to it. Can you find 2.3.4 within the `~/.rubies/` directory? 

I've only ever set the global version with the use of a version manager, like [chruby](https://github.com/postmodern/chruby)

**Comment by postmodern** [comment]
Try `ruby-install --system ruby 2.3.4` to install a global ruby into `/usr/local`.
