### ISSUE TITLE
"Unknown ruby version" warning for an already installed ruby version

### ISSUE THREAD

**Issue by eliduke** [postmodern/ruby-install#316]
I seriously hope I'm not waisting anyone's time here, but I'm seeing an interesting warning message that I can't totally figure out.

I am working on a project with a robust `script` directory with lots of tools for local development. One of said scripts (`script/server`) runs a couple checks things to make sure that the local environment is setup correctly. One of those checks tries to install ruby:
```
# read the ruby version from .ruby-version file
ruby_version=`cat .ruby-version`

echo "==> Installing Ruby: $ruby_version"
ruby-install ruby $ruby_version --no-reinstall
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby $ruby_version
```
And that is returning:
```
==> Installing Ruby: 2.5.1
*** Unknown ruby version 2.5.1. Proceeding anyways ...
>>> Ruby is already installed into /Users/eli/.rubies/ruby-2.5.1
```
This warning is not blocking me in anyway right now, I'm just curious about that "Unknown ruby" bit in there, so I decided to try just running the `ruby-install` command by itself:
```
$ ruby-install ruby 2.5.1 --no-reinstall
*** Unknown ruby version 2.5.1. Proceeding anyways ...
>>> Ruby is already installed into /Users/eli/.rubies/ruby-2.5.1
```
Am I missing something here?

**Comment by havenwood** [comment]
If you add the `--latest` flag then ruby-install will fetch the latest Ruby version metadata from [ruby-versions](https://github.com/postmodern/ruby-versions).

**Comment by havenwood** [comment]
The feature suggestion in #307 is related, as it would provide an answer to this question.

**Comment by eliduke** [comment]
@havenwood Cool! That did the trick. Thanks!
