### ISSUE TITLE
how to download faster with this prog in china?

### ISSUE THREAD

**Issue by glenlance** [postmodern/ruby-install#320]
my download speed is 3-5k/s,I don,t know what to do!!!

**Comment by havenwood** [comment]
The download speed will depend on the Ruby engine you're using, since CRuby, JRuby, and others are downloading from different locations.

The default CRuby download is on the Fastly CDN (https://cache.ruby-lang.org/pub/ruby). You can instead use a mirror in China with the `--mirror` flag, like:
```
ruby-install ruby --mirror https://ruby.taobao.org/mirrors/ruby/
```

**Comment by havenwood** [comment]
Another mirror in China is `https://cache.ruby-china.org/pub/ruby/`. See https://www.ruby-lang.org/en/downloads/mirrors/.
