### ISSUE TITLE
post_install hook not running

### ISSUE THREAD

**Issue by habibalamin** [postmodern/ruby-install#325]
I'm not sure if this applies to all the hooks, but I discovered this when I set up `chruby-default-gems` and it didn't do anything at all. I spent a while trying to figure out what was wrong with `chruby-default-gems`, but it seems to be fine itself.

When I do a:

```sh
post_install() { post_install && echo 'POST INSTALL' }
ruby-install ruby 2.3.2 -r /usr/local/var/versions/ruby
```

I expect `ruby-install` to echo a line `POST INSTALL` after the installation completes, but it behaves exactly the same as without the `post_install` declaration.

I'm using:

  - `zsh 5.6.2 (x86_64-apple-darwin17.7.0)`
  - `ruby-install: 0.7.0`
  - High Sierra 10.13.6

**Comment by postmodern** [comment]
The `post_install` function only works within ruby-install, and is explicitly defined for certain Ruby's, such as [jruby](https://github.com/postmodern/ruby-install/blob/0a683f0e60a7804a7066b608a56f1c46c2e0cd93/share/ruby-install/jruby/functions.sh#L20-L29). It is not meant to be user configurable. You could however setup an alias for ruby-install that does something like `original_ruby_install $* && my_post_install_hook`.
