### ISSUE TITLE
Fix the help for the --jobs option

### ISSUE THREAD

**Issue by RobertAudi** [postmodern/ruby-install#328]
The help for the `--jobs` option is missing the `=` sign; The [man page](https://github.com/postmodern/ruby-install/blob/master/doc/man/ruby-install.1.md#options) documents the option properly.

https://github.com/postmodern/ruby-install/blob/adaeb23ff136270b3c8526554f1f17fe6fbc57e0/share/ruby-install/ruby-install.sh#L43

https://github.com/postmodern/ruby-install/blob/ea2b8bbff87ea4340d965e72ac3acfb4ab1d1766/share/man/man1/ruby-install.1#L35

The error message thrown when omitting the `=` is kind of misleading:

```shell
$ ruby-install --jobs 4
!!! Unknown ruby: 4
```

The reason is that the number of jobs is used as the desired ruby version, even if the `--jobs` option is not the last one:

```shell
$ ruby-install --jobs 4 --cleanup --no-reinstall ruby
!!! Unknown ruby: 4
```

**Comment by postmodern** [comment]
Fixed in a0ee3814731061559852d775cbca178b6d76ae25 and 0a683f0e60a7804a7066b608a56f1c46c2e0cd93.
