### ISSUE TITLE
Doesn't work with Homebrew on Ubuntu

### ISSUE THREAD

**Issue by aar0nr** [postmodern/ruby-install#331]
Homebrew v1.9 added Linux support, but the ruby installation doesn't work on Ubuntu. I think this is because the scripts detect the package manager as ```apt``` before it detects ```brew```. Thus, it tries to install dependencies with ```apt``` , and also doesn't configure the dependency paths correctly.

**Comment by aar0nr** [comment]
If anyone else stumbles upon this, here is a workaround.

Manually install dependencies:

```brew install automake bison openssl readline libyaml gdbm libffi zlib```

Install latest ruby with:

```ruby-install --no-install-deps --package-manager brew ruby --  --with-zlib-dir=$(brew --prefix zlib)```

**Comment by FranklinYu** [comment]
How about `alias ruby-install='ruby-install --package-manager brew'`?

**Comment by postmodern** [comment]
Conflicted on whether we should default to always using the apt dependencies on ubuntu, or switch to brew if available?

**Comment by FranklinYu** [comment]
Personally I would rather use APT even when Homebrew is available. If we defaults to Homebrew I would make the alias myself.

**Comment by postmodern** [comment]
In 0.8.0 we made the package-manager detection OS/distro aware. However, I agree with @FranklinYu and would prefer/trust using the system's package manager over any additionally installed packages. `--package-manager brew` should override the auto-detection and use `brew install` and the `brew` dependencies.
