### ISSUE TITLE
Support for ruby 2.6.1 ?

### ISSUE THREAD

**Issue by racer1988** [postmodern/ruby-install#336]

**Comment by havenwood** [comment]
Ruby 2.6.1 is supported! Do you not see it after running `ruby-install --latest`?

**Comment by havenwood** [comment]
Closing as a duplicate of #335 and #275. We might want to consider making `ruby-install --latest` more prominent. Possibly just replacing `ruby-install` as the first example in the README.

**Comment by racer1988** [comment]
@havenwood Sorry for the late reply.

This is the console output of running simply `ruby-install` on macOS. I am using ruby-install coming from homebrew: 

```
 ruby-install --version
ruby-install: 0.7.0
```

``` 
ruby-install
Stable ruby versions:
  ruby:
    2.2.9
    2.3.6
    2.4.3
    2.5.0
  jruby:
    1.7.27
    9.2.0.0
  rbx:
    3.107
  truffleruby:
    1.0.0-rc6
  mruby:
    1.4.1
```

also installing Ruby 2.6.0 manually says that **the version of ruby is not supported** but will proceed anyway
