### ISSUE TITLE
Unable to install 2.5.3 (on Mac 10.14.3)

### ISSUE THREAD

**Issue by AlanDonohoe** [postmodern/ruby-install#339]
When I run:

`ruby-install 2.5.3`

I get:

`!!! Unknown ruby: 2.5.3`

When I run:

`ruby-install`

I get: 
```Stable ruby versions:
  ruby:
    2.3.8
    2.4.5
    2.5.4
    2.6.2
```

**Comment by havenwood** [comment]
It'd be:
```sh
ruby-install ruby-2.5.3
```
or
```sh
ruby-install ruby 2.5.3
```
or better yet, 2.5.4!

**Comment by AlanDonohoe** [comment]
Result... I'm an idiot... was even looking at the docs and missed that...

Thank you!
