### ISSUE TITLE
ruby-install rbx fails without llvm, but doesn't prompt that llvm should be brew installed

### ISSUE THREAD

**Issue by jm3** [postmodern/ruby-install#342]
I think this is just loose error reporting, not an actual bug, but when i run `ruby-install rbx`, it fails with: 

    Detected old configuration settings, forcing a clean build
      Checking for 'llvm-config': executing "/usr/local/Cellar/llvm/7.0.1/bin/llvm-config" failed
    ABORT: unable to set up LLVM

    Running 'configure' failed. Please check configure.log for more details.
    !!! Configuration of rbx 3.107 failed!

which I assumed just meant that i needed to `brew install llvm`. I did that, re-ran `ruby-install rbx`, and now it seems to be working. Seems like the rbx formula should list **llvm** as a dependency like the other rbx dependencies, report it to the user as such, and ideally auto-install on demand like the other brew dependencies (e.g. **openssl, readline, libyaml, gdbm**, see below install log)

    > ruby-install rbx-3.107
    >>> Installing rbx 3.107 into /Users/jm3/.rubies/rbx-3.107 ...
    >>> Installing dependencies for rbx 3.107 ...
    Warning: openssl 1.0.2q is already installed and up-to-date
    To reinstall 1.0.2q, run `brew reinstall openssl`
    Warning: readline 8.0.0 is already installed and up-to-date
    To reinstall 8.0.0, run `brew reinstall readline`
    Warning: libyaml 0.2.2 is already installed and up-to-date
    To reinstall 0.2.2, run `brew reinstall libyaml`
    Warning: gdbm 1.18.1 is already installed and up-to-date
    To reinstall 1.18.1, run `brew reinstall gdbm`
    >>> Downloading https://rubinius-releases-rubinius.../rubinius-3.107.tar.bz2 into ~jm3/src ...
    >>> Verifying rubinius-3.107.tar.bz2 ...
    >>> Extracting rubinius-3.107.tar.bz2 to /Users/jm3/src/rubinius-3.107 ...
    >>> Bundling rubinius 3.107 ...
    Successfully installed bundler-2.0.1
    Parsing documentation for bundler-2.0.1
    Done installing documentation for bundler after 2 seconds
    1 gem installed
    Could not locate Gemfile
    >>> Configuring rubinius 3.107 ...
    ------------------------------ Deprecation notice ------------------------------

    'configure' is deprecated and will be removed in the future.
    Use 'build.sh' to configure, build, package, and install Rubinius.

    --------------------------------------------------------------------------------
    Checking clang: found
    Checking clang++: found

    Detected old configuration settings, forcing a clean build
      Checking for 'llvm-config': executing "/usr/local/Cellar/llvm/7.0.1/bin/llvm-config" failed
    ABORT: unable to set up LLVM

    Running 'configure' failed. Please check configure.log for more details.
    !!! Configuration of rbx 3.107 failed!

**Comment by postmodern** [comment]
Appears rbx updated their build system. In the past on macOS, they would download their own copy of llvm, so we omitted it from the `brew` dependencies.

**Comment by postmodern** [comment]
Rubinius support was removed due to inactivity. Closing this.
