### ISSUE TITLE
Install Ruby on darwin 18

### ISSUE THREAD

**Issue by carminemilieni** [postmodern/ruby-install#352]
I have MacOS Mojave 10.14.16 on execute command from terminal
`ruby-install ruby`
i received this error 
`Error: Current platform "darwin 18" does not match expected platform "darwin 16"
Error: If you upgraded your OS, please follow the migration instructions: https://trac.macports.org/wiki/Migration
OS platform mismatch
    while executing
"mportinit ui_options global_options global_variations"
Error: /opt/local/bin/port: Failed to initialize MacPorts, OS platform mismatch
!!! Installing dependencies failed!`

**Comment by FranklinYu** [comment]
Are you able to use MacPorts as usual?

**Comment by havenwood** [comment]
Closing since this looks like a MacPorts issue. Please reopen if the issue persists.
