### ISSUE TITLE
Ruby < 2.4 fails with homebrew due to openssl

### ISSUE THREAD

**Issue by bbck** [postmodern/ruby-install#363]
Homebrew has removed openssl 1.0 and now installs 1.1 which is causing all builds of MRI ruby 2.3 or less to fail.

I was able to get around this by installing the deleted openssl formula with homebrew and passing the path

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8b9d6d688f483a0f33fcfc93d433de501b9c3513/Formula/openssl.rb
ruby-install ruby 2.3.8 -- --with-openssl-dir=/usr/local/opt/openssl
```

**Comment by eliduke** [comment]
I'm trying this, but it looks like that flag isn't actually working:

```
$ openssl version
OpenSSL 1.0.2t  10 Sep 2019
$ which openssl
/usr/local/opt/openssl/bin/openssl
$ ruby-install ruby 2.3.3 -- --with-openssl-dir=/usr/local/opt/openssl/bin/openssl
>>> Installing ruby 2.3.3 into /Users/eliduke/.rubies/ruby-2.3.3 ...
>>> Installing dependencies for ruby 2.3.3 ...
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
Warning: bison 3.5 is already installed and up-to-date
To reinstall 3.5, run `brew reinstall bison`
Warning: readline 8.0.1 is already installed and up-to-date
To reinstall 8.0.1, run `brew reinstall readline`
Warning: libyaml 0.2.2 is already installed and up-to-date
To reinstall 0.2.2, run `brew reinstall libyaml`
Warning: gdbm 1.18.1 is already installed and up-to-date
To reinstall 1.18.1, run `brew reinstall gdbm`
Warning: libffi 3.2.1 is already installed and up-to-date
To reinstall 3.2.1, run `brew reinstall libffi`
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1d.mojave.bottle.tar.gz
Already downloaded: /Users/eliduke/Library/Caches/Homebrew/downloads/ad40ab0d39bcc1e58d4e87515460f704efd195352ae376f7b28994b71c640810--openssl@1.1-1.1.1d.mojave.bottle.tar.gz
==> Pouring openssl@1.1-1.1.1d.mojave.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1d: 7,983 files, 17.9MB
>>> Downloading https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.bz2 into /Users/eliduke/src ...
>>> Verifying ruby-2.3.3.tar.bz2 ...
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/md5sum
  Reason: image not found
!!! Invalid md5 checksum for /Users/eliduke/src/ruby-2.3.3.tar.bz2
!!!   expected: 04b9c461a2bc1eec0535ad1947cad4fb
!!!   actual:   
!!! Verification of ruby-2.3.3.tar.bz2 failed!
```

As you can see, it still grabs openssl v1.1. What am I doing wrong here?

**Comment by eliduke** [comment]
OK. I got it working for me, but the missing piece of the puzzle was `brew switch`.  Without it, `ruby-install` kept trying to use openssl 1.1 and then the install would fail.

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8b9d6d688f483a0f33fcfc93d433de501b9c3513/Formula/openssl.rb
brew switch openssl 1.0.2t
ruby-install ruby 2.3.3 -- --with-openssl-dir=/usr/local/opt/openssl
```

Hope this helps others out there who might be searching.

**Comment by ravicious** [comment]
I wasn't able to issue `brew install` with that URL because I already have openssl@1.1 installed.

Instead I did this (courtesy of https://github.com/rbenv/ruby-build/issues/1353#issuecomment-573414540):

```
brew install rbenv/tap/openssl@1.0
ruby-install ruby 2.3.3 --no-install-deps -- --with-openssl-dir=$(brew --prefix openssl@1.0) --disable-install-doc
```

**Comment by hosamaly** [comment]
I used homebrew's tap, but I had to export `CPPFLAGS` and `LDFLAGS` to get it working...
https://stackoverflow.com/a/61915791/41283

**Comment by esambo** [comment]
It would be nice to get this workaround properly documented, eg: _Ruby versions < 2.4 #370_

**Comment by schneems** [comment]
I'm unable to brew install that version of openssl

```
$ brew install rbenv/tap/openssl@1.0
Updating Homebrew...
Error: No available formula or cask with the name "rbenv/tap/openssl@1.0".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```

**Comment by schneems** [comment]
I missed this part in front:

```
$ brew tap rbenv/tap
$ brew install rbenv/tap/openssl@1.0
```

That got openssl 1.0 installed. I'm still getting failures getting 2.2.10 to install though.

**Comment by postmodern** [comment]
FYI [Ruby 2.4 reached End-of-Life](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/#:~:text=We%20announce%20that%20all%20support,Ruby%202.4%20series%20has%20ended.) on March 31st. ruby-install does not officially support unmaintained versions due to these kind of issues. Either the openssl bindings would need to be updated for openssl 1.1, or you have to try compiling against openssl 1.0. Either way someone has to maintain the EoLed version of Ruby or the EoLed version of openssl. It's usually less work to just update your project to a maintained version of Ruby.

**Comment by postmodern** [comment]
Going to close this since ruby-install only installs the upstream rubies as-is. I am open to people contributing documentation on how to compile older unsupported rubies against older versions of openssl or gcc. Although, I strongly recommend people upgrade to an actively maintained version of ruby in order to take advantage of better support, security updates, etc.
