### ISSUE TITLE
Switch from tar.bz2 to tar.gz for CRuby archives

### ISSUE THREAD

**Issue by havenwood** [postmodern/ruby-install#366]
Ruby Core has decided to stop shipping `.tar.bz2` archives. See https://bugs.ruby-lang.org/issues/16483

**Comment by havenwood** [comment]
I suspect we should go ahead and move from `.tar.bz2` to `.tar.xz` or `.tar.gz` for CRuby and cut a new release of ruby-install soon to minimize disruption with Ruby 3.0 not having a `.tar.bz2` archive.

**Comment by havenwood** [comment]
@postmodern I'm assuming we'll want to use `.tar.gz`?

**Comment by postmodern** [comment]
@havenwood wrt `tar.xz`, we'd need to double check whether additional dependencies need to be installed for `xz` for the other package managers. I'm pretty sure Ubuntu supports it out-of-the-box with `tar -xJf`, but maybe certain versions of macOS may require using `unxzv` from xz-utils? We could switch back to `tar.gz`, but with a penalty to bandwidth/disk-space.

**Comment by todd-a-jacobs** [comment]
With the release of ruby-3.0.0-preview1, bzip2 is no longer supported. The preview release will fail the validation check, and other than turning off validation there don't appear to be any knobs to twiddle to install a different archive type.

**Comment by postmodern** [comment]
Does macOS ship with an `xz`/`unxz` command now, or would we need to add it to the dependencies?

**Comment by havenwood** [comment]
No, macOS doesn't ship with `xz`. There's a Homebrew package for `xz` but since 10.9 macOS has supported xz with `tar`. We should be able to rely on `tar -x` since it's now available in all supported macOS versions.

**Comment by postmodern** [comment]
Thoughts on dynamically selecting the desired archive format, given whether `gunzip`, `bunzip2,` or `unxz` are installed?

**Comment by havenwood** [comment]
I like the idea of configurable decompression format. +1

On another note, @eregon pointed out [possible issues](https://bugs.ruby-lang.org/issues/16483#note-8) preventing `xz` from being the sole choice if more compression formats are removed.

**Comment by eregon** [comment]
@havenwood 
> We should be able to rely on `tar -x` since it's now available in all supported macOS versions.

`tar -x` is just the extract flag, right?
On Linux the flag for xz seems to be `-J` or `--xz`.
Or do you mean `tar xf foo.tar.xz` works on all supported macOS versions?

Given the sizes of Ruby archives, I would always go with the tried-and-true-and-proved `.tar.gz`.
For 2.7.2:
`.tar.gz`: 16836767, 16MB
`.tar.bz2`: 14708724, 14MB
`.tar.xz`: 12037052, 11.5MB

All these are tiny, it seems unlikely the difference is relevant when installing CRuby.

**Comment by havenwood** [comment]
@eregon With macOS `tar` it's also `-J, --xz` for compressing but no extra flag needed with `-x` for extracting. The manpage does mention "unlike other tar implementations."

> Note that, unlike other tar implementations, this implementation recognizes XZ compression automatically when reading archives.

**Comment by eregon** [comment]
Not sure why but ruby-3.0.0-preview1 still has a bz2: https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/
Maybe because they realized Ruby installers did not have time to adapt to that change yet?

**Comment by postmodern** [comment]
Hmm macOS supporting `tar -xJ` but not having an `unxz` command throws a wrench in my plans to auto-detect `xz` support. In that case, we'll have to add it as a dependency. Should we always install `xz` from homebrew, or rely on macOS's `tar`? Guessing not many people still use macOS < 10.9?

**Comment by postmodern** [comment]
@havenwood am I correct in assuming macOS's `tar` can utilize `unxz` if installed, or did Apple vendor xz-utils into the `tar` binary?

I'm torn between auto-detecting `unxz` (thus choosing the `tar.xz` archive, otherwise falling back to `tar.gz`) or adding `xz` as a dependency of Ruby. While the `xz` compression format does have some technical issues which may cause problems in the future, it is gaining popularity and results in less bandwidth/disk-space being used.

**Comment by havenwood** [comment]
@postmodern The latter. They vendored xz-utils into `tar` in 10.9 and don't ship `unxz`.

**Comment by postmodern** [comment]
This should be resolved by the [use_tar_xz_for_ruby](https://github.com/postmodern/ruby-install/compare/0.8.0...use_tar_xz_for_ruby) branch. Added support for extracting `.tar.xz` archives with `tar -xJf`, changed `ruby_archive` in `ruby/functions.sh`, and added xz-utils as a dependency (excluding macOS and FreeBSD which provide it as part of the base system).

**Comment by postmodern** [comment]
Merged use_tar_xz_for_ruby branch into master. Will release 0.8.0 tomorrow.

**Comment by postmodern** [comment]
0.8.0 has been released!
