### ISSUE TITLE
Proposal: output system install command for openssl?

### ISSUE THREAD

**Issue by esotericpig** [postmodern/ruby-install#367]
Recently, I upgraded my system, Fedora.

When trying to call `ruby-install ruby 2.6.5`, I got openssl issues, which seems to be a common issue here:

```
>>> Installing dependencies for ruby 2.6.5 ...
Error: 
 Problem: problem with installed package compat-openssl10-devel-1:1.0.2o-8.fc31.x86_64
```

Even though it tells me the error and the problem (openssl), I had no idea what command it's trying to run with `dnf`.

I fixed the issue calling this:

```
sudo dnf install openssl-devel --allowerasing
```

Since it's such a common issue and so dependent on the system, it'd be best to output what command is trying to be run so that users can easily fix it themselves in their system, like this:

```
>>> Installing dependencies for ruby 2.6.5 ...
If you have issues, please try this command in your system:
Running: sudo dnf install openssl-devel
Error: 
 Problem: problem with installed package compat-openssl10-devel-1:1.0.2o-8.fc31.x86_64
```

With that `Running` line in a green color or something, then this will prompt users to try that themselves and fix the issue themselves on their specific system.

As of now, you have to kind of guess what is being called, and it makes people create issues here, when it isn't even `ruby-install`'s fault.

**Comment by postmodern** [comment]
We could add debugging messages and a `--debug` option. We'd also need to identify the critical commands that need to be logged.

**Comment by postmodern** [comment]
The 0.9.0 branch now has a `-D,--debug` option that will output all package manager commands and `./configure` commands. fb4779c81a9d0c8eb483e0ad7ca9fdab5f4f2d90
