### ISSUE TITLE
Ruby fails to link (for me) on OSX Mojave 10.14.5

### ISSUE THREAD

**Issue by Lazrhog** [postmodern/ruby-install#371]
Not sure whether the OSX version matters... I'd appreciate a workaround if there is one :)

command I ran is CC=/usr/bin/gcc rvm install ruby
$LDFLAGS is -L/usr/local/opt/openssl@1.1/lib
$CPPGLAGS is -I/usr/local/opt/openssl@1.1/include

My error log is 

[2020-05-30 14:44:22] __rvm_make
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /Users/xxxx/.rvm/src/ruby-2.7.0
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/Cellar/libtool/2.4.6_1/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/xxxx/.rvm/bin
command(2): __rvm_make -j8
++ make -j8
	BASERUBY = /usr/bin/ruby --disable=gems
	CC = /usr/bin/gcc
	LD = ld
	LDSHARED = /usr/bin/gcc -dynamiclib
	CFLAGS = -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -std=gnu99  -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -DCANONICALIZATION_FOR_MATHN -I. -I.ext/include/x86_64-darwin18 -I./include -I. -I./enc/unicode/12.1.0
	CPPFLAGS = -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   
	DLDFLAGS = -L/usr/local/opt/openssl@1.1/lib -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -install_name /Users/xxxx/.rvm/rubies/ruby-2.7.0/lib/libruby.2.7.dylib -compatibility_version 2.7 -current_version 2.7.0  -fstack-protector-strong -framework Security -framework Foundation  -fstack-protector-strong -framework Security -framework Foundation  
	SOLIBS = -lpthread -ldl -lobjc
	LANG = en_GB.UTF-8
	LC_ALL = 
	LC_CTYPE = 
	MFLAGS = - --jobserver-fds=4,5 -j
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
compiling ./main.c
compiling dmydln.c
compiling miniinit.c
compiling dmyext.c
translating probes probes.d
compiling ast.c
compiling bignum.c
compiling class.c
compiling compar.c
. ./vm_opts.h
compiling compile.c
compiling complex.c
compiling cont.c
compiling debug.c
compiling debug_counter.c
compiling dir.c
compiling dln_find.c
compiling encoding.c
compiling enum.c
compiling enumerator.c
compiling error.c
compiling eval.c
compiling file.c
compiling gc.c
compiling hash.c
compiling inits.c
compiling io.c
compiling iseq.c
compiling load.c
compiling marshal.c
compiling math.c
making mjit_config.h
compiling mjit_compile.c
compiling node.c
compiling numeric.c
compiling object.c
compiling pack.c
compiling parse.c
compiling proc.c
compiling process.c
compiling random.c
compiling range.c
compiling rational.c
compiling re.c
compiling regcomp.c
compiling regenc.c
compiling regerror.c
compiling regexec.c
compiling regparse.c
compiling regsyntax.c
compiling ruby.c
compiling safe.c
compiling signal.c
compiling sprintf.c
compiling st.c
compiling strftime.c
compiling string.c
compiling struct.c
compiling symbol.c
compiling thread.c
compiling time.c
compiling transcode.c
compiling transient_heap.c
compiling util.c
compiling variable.c
compiling vm.c
compiling vm_backtrace.c
compiling vm_dump.c
compiling vm_trace.c
compiling ./missing/explicit_bzero.c
compiling ./missing/setproctitle.c
compiling addr2line.c
compiling dmyenc.c
compiling dln.c
config.status: creating ruby-runner.h
compiling localeinit.c
compiling array.c
compiling mjit.c
assembling coroutine/amd64/Context.S
compiling enc/ascii.c
compiling enc/us_ascii.c
compiling enc/unicode.c
compiling enc/utf_8.c
compiling enc/trans/newline.c
./revision.h unchanged
compiling version.c
building rb_mjit_header.h
rb_mjit_header.h updated
linking miniruby
Undefined symbols for architecture x86_64:
  "_coroutine_transfer", referenced from:
      _fiber_setcontext in cont.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [miniruby] Error 1
++ return 2

**Comment by postmodern** [comment]
You appear to be using `rvm install` to install the ruby. You might want to submit the issue over to the [RVM issue tracker](https://github.com/rvm/rvm/issues).

**Comment by dpa99c** [comment]
@Lazrhog did you solve this?
I'm getting the same on Big Sur after upgrading from Catalina.
I get the same compilation error whether I use `ruby-install`, `rvm` or `rbenv`

```
compiling version.c
linking miniruby
Undefined symbols for architecture x86_64:
  "_coroutine_transfer", referenced from:
      _fiber_setcontext in cont.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [miniruby] Error 1
```

@postmodern apologies for referencing a closed issue but this is the only reference I can find to it

**Comment by mic-kul** [comment]
@dpa99c did you manage to solve it? I'm getting same issue on `Catalina 10.15.7`

**Comment by dpa99c** [comment]
> @dpa99c did you manage to solve it? I'm getting same issue on `Catalina 10.15.7`

No I still haven't solved it on Catalina despite a clean install

**Comment by cayleyh** [comment]
For future reference: the solution for me was similar to @mic-kul solution referenced https://github.com/rbenv/ruby-build/issues/1723#issuecomment-872548168, expect I didn't have any version of `binutils` installed, so I had to install one and correctly configure it in my path (On Monterey 12.0.1, M1 MacBook Pro).
