### ISSUE TITLE
Making it easier to find the latest Ruby version.

### ISSUE THREAD

**Issue by peterb** [postmodern/ruby-install#384]
You have to run `ruby-install -L` to download the latest versions before running ruby-install. This isn't so intuitive for occasional users. Would it be worth including a last-updated timestamp, or running with the -L option by default?

**Comment by postmodern** [comment]
We probably want to enable auto-downloading for certain edge-cases:

* When no version is given.
* When the version is not-fully qualified (ex: `3.0`).
* When the version cannot be found within `versions.txt`.

**Comment by peterb** [comment]
I can take a look at implementing this or we could take a look together.

**Comment by postmodern** [comment]
Another idea is to rename `--latest` to `--update` and have it update the ruby-versions before doing the main action. `ruby-install --update` and `ruby-install --update ruby` seem more obvious as to what they're doing? Adding more auto-downloading is doable, but would complicate the version expansion logic.

**Comment by postmodern** [comment]
I added the new `-U,--update` option and it will be released in 0.9.0. I will also probably attempt to add the complex logic of if the version isn't known, update the versions/checksums, and try resolving the version again.

**Comment by postmodern** [comment]
Implemented an additional logic check for if the ruby version is not yet known, then download the versions. bbc327d80f094a8b24c446ca36da7b60d9579fb8

Will be released in 0.9.0.
