### ISSUE TITLE
Can't install ruby-3.0.0

### ISSUE THREAD

**Issue by juanmanuelramallo** [postmodern/ruby-install#388]
# To reproduce
```
ruby-install --latest ruby
```

# Version
```
ruby-install: 0.7.1
```

# Error message
Downloading https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.bz2 into /Users/<username>/src ...
--2020-12-25 13:56:57--  https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.bz2
Resolving cache.ruby-lang.org (cache.ruby-lang.org)... 151.101.1.178, 151.101.65.178, 151.101.129.178, ...
Connecting to cache.ruby-lang.org (cache.ruby-lang.org)|151.101.1.178|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-25 13:56:58 ERROR 404: Not Found.

!!! Download of https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.bz2 failed!

Am I missing something?

**Comment by juanmanuelramallo** [comment]
Didn't realize there was a new version of ruby-install. I installed 0.8.1 and everything worked like a charm

**Comment by sergiopantoja** [comment]
I ran into the same issue. Thanks for the tip!
