### ISSUE TITLE
ruby-install list can't download file on v.0.81.0

### ISSUE THREAD

**Issue by mediafinger** [postmodern/ruby-install#391]
```
$> ruby-install --version
  ruby-install: 0.8.1

$> ruby-install list
  >>> Updating list versions ...
  !!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/list/versions.txt to ...
  !!! Failed to download list versions!
```

**Comment by ragaskar** [comment]
See this issue: https://github.com/postmodern/ruby-install/issues/361

tl;dr: try `brew upgrade wget`

I had a similar issue and upgrading wget fixed it.

**Comment by tjoyal** [comment]
[RTFM](https://github.com/postmodern/ruby-install/blob/master/README.md#synopsis) (Read the manual), something I myself didn't do and ended up here...

`wget` as linked was an issue but is not what is happening here.

What you are looking for is "List the latest versions":
```
ruby-install --latest
```

The following commands try to install a Ruby of the associated type, which as one would expect do not exist.
```
ruby-install list
ruby-install update
ruby-install <anything>
```


Hopefully that helps people ending up reading this issue 😸
