### ISSUE TITLE
ruby-install fails in cases where homebrew is installed with a different prefix

### ISSUE THREAD

**Issue by kthelgason** [postmodern/ruby-install#392]
If homebrew is installed outside of usr/local then the `sudo brew` command will fail as the `PATH` variable in the execution environment most likely won't include the `brew` executable.

One idea is to pass `--preserve-env=PATH` to the invocation to `sudo`, but that requires the executing user to have the `brew` executable on their `PATH`. Another solution would be to get the full path to the executable using `brew --prefix` but that has the same requirement. Is that an acceptable constraint?

I'm happy to provide a patch.

**Comment by postmodern** [comment]
PR #396 has been merged which will not use `sudo` to run `brew`, if homebrew was installed by the current user.

**Comment by postmodern** [comment]
0.8.2 and 0.8.3 were released. This should be fixed.
