### ISSUE TITLE
Track TruffleRuby FHS issue

### ISSUE THREAD

**Issue by missingcharacter** [postmodern/ruby-install#398]
The issue I'm talking about is https://github.com/oracle/truffleruby/issues/1389 and the reason I think this issue should be linked to this project is `truffleruby` cannot be currently installed using `--system` (`/usr/local`), even when the issue is not something this project will fix users of `ruby-install` are affected by it and seeing a connection between the 2 projects would probably save people time when they realize `truffleruby` cannot be installed using `--system`.

Note: I only became aware of this problem after I noticed `truffleruby` was supported, see below:

```shell
ruby-install --latest
>>> Downloading latest ruby versions ...
>>> Downloading latest jruby versions ...
>>> Downloading latest rbx versions ...
>>> Downloading latest truffleruby versions ...
>>> Downloading latest truffleruby-graalvm versions ...
>>> Downloading latest mruby versions ...
Stable ruby versions:
  ruby:
    2.6.7
    2.7.3
    3.0.1
  jruby:
    9.2.16.0
  rbx:
    5.0
  truffleruby:
    21.0.0
  truffleruby-graalvm:
    21.0.0
  mruby:
    2.1.2
```

and later I tried to install `truffleruby` in a container

**Comment by eregon** [comment]
Maybe `ruby-install` should warn or error when trying to install truffleruby with `--system`?

I wouldn't bet on https://github.com/oracle/truffleruby/issues/1389 being solved very soon, it's a large effort for what seems a fairly low gain, most rubyists already install Rubies in their own directory and not randomly mix them with system files (which feels like it always causes more problem than it solves).

**Comment by missingcharacter** [comment]
@eregon and @postmodern what do you think of this? https://github.com/postmodern/ruby-install/pull/401
