### ISSUE TITLE
3.0.1 not found

### ISSUE THREAD

**Issue by crudson** [postmodern/ruby-install#400]
Getting a 404 when trying to get from the default  https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2

Trying to point to a release that is there (with -u) doesn't work as they are not .bz2 (I don't think ruby-install handles .gz?), and I checked the mirrors on ruby-lang.org.

**Comment by postmodern** [comment]
ruby-install >= 0.8.0 switched to downloading `.tar.xz` release archives after ruby-core announced they would be dropping support for `.tar.bz2` release archives. Try upgrading ruby-install.

**Comment by crudson** [comment]
Oh excellent, that makes sense with what I'm seeing. Thanks!
