### ISSUE TITLE
 ruby-install ruby 3.0.2 fails since bz2 files no longer published

### ISSUE THREAD

**Issue by professor** [postmodern/ruby-install#404]
Looks like bz2 files are no longer published.

https://cache.ruby-lang.org/pub/ruby/3.0/
```
ruby-3.0.0-preview1.tar.bz2
ruby-3.0.0-preview1.tar.gz
ruby-3.0.0-preview1.tar.xz 
ruby-3.0.0-preview1.zip
ruby-3.0.0-preview2.tar.gz
ruby-3.0.0-preview2.tar.xz 
ruby-3.0.0-preview2.zip 
ruby-3.0.0-rc1.tar.gz 
ruby-3.0.0-rc1.tar.xz 
ruby-3.0.0-rc1.zip 
ruby-3.0.0.tar.gz 
ruby-3.0.0.tar.xz
ruby-3.0.0.zip 
ruby-3.0.1.tar.gz 
ruby-3.0.1.tar.xz 
ruby-3.0.1.zip
ruby-3.0.2.tar.gz 
ruby-3.0.2.tar.xz 
ruby-3.0.2.zip 
```

Error
Downloading https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.2.tar.bz2 into /Users/pivotal/src ...
--2021-07-15 10:37:56--  https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.2.tar.bz2
Resolving cache.ruby-lang.org (cache.ruby-lang.org)... 151.101.189.178
Connecting to cache.ruby-lang.org (cache.ruby-lang.org)|151.101.189.178|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

**Comment by postmodern** [comment]
Support for downloading/extracting `.tar.xz` was added in [ruby-install 0.8.0](https://github.com/postmodern/ruby-install/blob/master/ChangeLog.md#080--2020-12-09). Upgrade to ruby-install >= 0.8.0 and it should work.
