### ISSUE TITLE
Add option to remove 'ruby-' prefix

### ISSUE THREAD

**Issue by havenwood** [postmodern/ruby-install#44]
Add an option to remove the 'ruby-' prefix from the Ruby name. For example, ruby-2.0.0-p195 would become 2.0.0-p195.

**Comment by bronson** [comment]
This seems inconsistent...?  Either it's called `mri` and just another ruby, or it's called `ruby` and is the intuitive default.

**Comment by havenwood** [comment]
@bronson For each of the Rubies the engine name matches the `RUBY_ENGINE` value. So `"ruby"` for MRI, `"mruby"` for mruby, `"jruby"` for JRuby and `"rbx"` for Rubinius.

So it's `RUBY_ENGINE`-`RUBY_ENGINE_VERSION`.

**Comment by bronson** [comment]
Ah right, I'd forgotten about RUBY_ENGINE.

Like anything, it makes sense once you see the internals.  :)

**Comment by postmodern** [comment]
@bronson we settled on naming the rubies after their primary executable (MRI -> ruby, Rubinius -> rbx). This also nicely aligns with `RUBY_ENGINE`. I also don't think it's fair to the other rubies to give special treatment to MRI.
