### ISSUE TITLE
Publish ruby-install as an apt package for Ubuntu

### ISSUE THREAD

**Issue by stillhart** [postmodern/ruby-install#489]
## Description

I am on Ubuntu. I would love to install ruby-install via apt and not build from source.

## Steps To Reproduce

```sh
apt install ruby-install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ruby-install
```

## Expected Behavior

It's installing ruby-install from package manager

## Actual Behavior

It fails and I need to build ruby-install from source instead

## Environment

Linux ubuntu-4gb-fsn1-1 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## Note

I assume there is no Ubuntu package for a reason, but I hope for the small chance that there isn't one. Feel free to close this if needed. It's more of a feature request than a bug. I have absolutely 0 experience in Ubuntu packages, so I can't really help with a MR.

**Comment by postmodern** [comment]
Debian's package building tools have very strict standards, and I don't have the bandwidth to modify ruby-install's Makefile to pass all of their validations. If you would like to tackle setting up the necessary Debian package definition files, I would accept a PR.
