### ISSUE TITLE
TruffleRuby[GraalVM] - homebrew openssl dependency upgrade to v3

### ISSUE THREAD

**Issue by beelleau** [postmodern/ruby-install#490]
## Description

`ruby-install truffleruby` and `ruby-install truffleruby-graalvm` fail uisng homebrew on MacOS

## Steps To Reproduce

Steps to reproduce the bug:
1. `$ ruby-install truffleruby`
or
2. `$ ruby-install truffleruby-graalvm`

## Expected Behavior

brew would normally install dependencies (which can be observed as successful when using `ruby-install ruby`). 

## Actual Behavior

 $ ruby-install truffleruby
>>> Updating truffleruby versions ...
>>> Installing truffleruby 24.1.1 into /Users/beelleau/.rubies/truffleruby-24.1.1 ...
>>> Installing dependencies for truffleruby 24.1.1 ...
Warning: libyaml 0.2.5 is already installed and up-to-date.
To reinstall 0.2.5, run:
  brew reinstall libyaml
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.
Error: openssl@1.1 not installed
Warning: libyaml 0.2.5 already installed
!!! Installing dependencies failed!

## Environment

    $ ruby-install --version
    ruby-install: 0.9.3
    
    $ uname -a
    Darwin <myhostname>.<mydomain> 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 18:51:28 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8112 arm64 arm Darwin
    
    $ cc --version
     Apple clang version 16.0.0 (clang-1600.0.26.6)
     Target: arm64-apple-darwin24.2.0
     Thread model: posix
     InstalledDir: /Library/Developer/CommandLineTools/usr/bin

    $ openssl version
    (not relevant but here it is anyways)
    OpenSSL 3.4.0 22 Oct 2024 (Library: OpenSSL 3.4.0 22 Oct 2024)
    

## Updates?
I think the share/truffleruby[-graalvm]/dependencies.txt file just needs to be updated. After updating these to openssl@3 it "worked on my machine :)"

**Comment by postmodern** [comment]
@beelleau I will try to release 0.9.4 in the next few days. Note there is also a 0.10.0 branch I will also need to rebase, which converts `dependencies.txt` into `dependencies.sh` to allow for dynamically defined dependencies. I also need to release 0.10.0 sometime soon.

**Comment by beelleau** [comment]
@postmodern I'm going to reach out to you via email, but I am able to help with testing if needed.
